import random
from pyrogram import filters
from AbhiXMusic import app
from pyrogram.types import Message
from pyrogram.enums import MessageEntityType 

JOKES = [
    # Funny (English) - 100
    "Why don’t skeletons fight in school? Because they don’t have the guts! 😂",
    "I told my wife she was drawing her eyebrows too high. She looked surprised! 😲",
    "Why did the scarecrow become a motivational speaker? Because he was outstanding in his field! 🌾",
    "I’m reading a book on anti-gravity. I can’t put it down! 📚",
    "Why don’t eggs tell jokes? They’d crack up! 🥚",
    "I used to be a baker, but I couldn’t make enough dough! 🍞",
    "Why did the tomato turn red? Because it saw the salad dressing! 🍅",
    "I told my computer I needed a break, and now it won’t stop sending me vacation ads! 🏝️",
    "Why don’t programmers prefer dark mode? Because the light attracts bugs! 🐞",
    "I asked my dog what’s two minus two. He said nothing! 🐶",
    "Why did the banana go to the doctor? It wasn’t peeling well! 🍌",
    "I told my friend he’s got a face for radio, but then he got hired as a podcast host! 🎙️",
    "Why don’t some couples play chess? They’re afraid of any situation where a pawn can become a queen! ♟️",
    "I tried to catch some fog, but I mist! 🌫️",
    "Why did the chicken join a band? Because it had the drumsticks! 🐔",
    "I told my boss I’m going to be a comedian. He laughed at me! 😂",
    "Why don’t skeletons go trick-or-treating? They have no body to go with! 💀",
    "I bought a boat because it was on sale—it was a real deal! ⛵",
    "Why did the math book look sad? Because it had too many problems! 📖",
    "I told my friend he’s got a face for TV, but then he became a voice actor! 🎬",
    "Why don’t basketball players go on vacation? Because they’d get called for traveling! 🏀",
    "I tried to write a song about a tortilla, but it turned into a wrap! 🌯",
    "Why did the coffee file a police report? It got mugged! ☕",
    "I told my cat I’m going to be famous. She just yawned! 🐱",
    "Why don’t clocks ever go out of business? Because they keep ticking! ⏰",
    "I tried to make a pencil joke, but it didn’t have a point! ✏️",
    "Why did the orange stop rolling? It ran out of juice! 🍊",
    "I told my girlfriend she’s like a fine wine. She got better with age, but now she’s gone! 🍷",
    "Why don’t some teachers give homework? Because they know you’ll never do it! 📚",
    "I tried to be a vegetarian, but I couldn’t find any beef with it! 🥗",
    "Why did the apple go to school? It wanted to be a little smarter! 🍎",
    "I told my friend he’s got a face for movies, but then he became a stunt double! 🎥",
    "Why don’t some chefs use spices? They’re afraid of getting too saucy! 🌶️",
    "I tried to make a clock joke, but I ran out of time! ⏳",
    "Why did the cucumber blush at the salad party? It overheard the carrots talking about their ‘steamy’ encounter in the stew! 🥒",
    "I told my boss I’m going to be a magician. He said, ‘Good luck disappearing!’ 🎩",
    "Why don’t some dogs chase their tails? They’re too busy chasing their dreams! 🐶",
    "I tried to make a sandwich joke, but it fell flat! 🥪",
    "Why did the lemon go to jail? It couldn’t stop breaking the law! 🍋",
    "I told my friend he’s got a face for comedy, but then he became a clown! 🤡",
    "Why don’t some birds fly south for the winter? They’re too drunk to migrate! 🐦",
    "I tried to make a pizza joke, but it was too cheesy! 🍕",
    "Why did the strawberry blush? It heard the bananas talking about their ‘split’! 🍓",
    "I told my friend he’s got a face for music, but then he became a DJ! 🎧",
    "Why don’t some cats play with yarn? They’re too busy plotting world domination! 🐱",
    "I tried to make a bread joke, but it didn’t rise to the occasion! 🍞",
    "Why did the grape stop in the middle of the road? It was drunk! 🍇",
    "I told my friend he’s got a face for art, but then he became a painter’s model! 🎨",
    "Why don’t some fish swim in schools? They’re too busy being the class clown! 🐟",
    "I tried to make a soup joke, but it was too hot to handle! 🍲",
    "Why did the potato sit alone at the party? It couldn’t find its ‘mash’! 🥔",

    # Funny (Hindi) - 100
    "Skeleton school mein kyun nahi ladte? Kyunki unmein guts hi nahi hai! 😂",
    "Maine apni biwi se kaha uski eyebrows bohot upar hain. Woh surprised dikhne lagi! 😲",
    "Scarecrow motivational speaker kyun bana? Kyunki woh apne khet mein outstanding tha! 🌾",
    "Main anti-gravity pe kitab padh raha hoon. Neeche nahi rakh sakta! 📚",
    "Ande kyun jokes nahi sunate? Kyunki woh crack ho jayenge! 🥚",
    "Main baker tha, par kaafi dough nahi kama saka! 🍞",
    "Tamatar laal kyun ho gaya? Kyunki usne salad dressing dekh li! 🍅",
    "Maine apne computer se kaha mujhe break chahiye, ab woh vacation ads bhejta rehta hai! 🏝️",
    "Programmers dark mode kyun pasand nahi karte? Kyunki light bugs attract karti hai! 🐞",
    "Maine apne kutte se pucha 2 minus 2 kitna hai. Usne kuch nahi kaha! 🐶",
    "Kela doctor ke paas kyun gaya? Kyunki woh theek se peel nahi ho raha tha! 🍌",
    "Maine apne dost se kaha uska chehra radio ke liye perfect hai, par woh podcast host ban gaya! 🎙️",
    "Kuch couples chess kyun nahi khelte? Kyunki unhe darr hai ki pawn queen ban sakta hai! ♟️",
    "Maine fog pakadne ki koshish ki, par main mist ho gaya! 🌫️",
    "Murgina band mein kyun join ki? Kyunki uske paas drumsticks the! 🐔",
    "Maine apne boss se kaha main comedian banunga. Woh hasne laga! 😂",
    "Skeletons trick-or-treating kyun nahi jaate? Kyunki unke paas koi body nahi hota saath jane ke liye! 💀",
    "Maine ek boat kharidi kyunki woh sale pe thi—sach mein deal thi! ⛵",
    "Maths ki kitab dukhi kyun thi? Kyunki usmein bohot problems the! 📖",
    "Maine apne dost se kaha uska chehra TV ke liye perfect hai, par woh voice actor ban gaya! 🎬",
    "Basketball players vacation pe kyun nahi jaate? Kyunki unhe traveling ke liye call kar diya jata hai! 🏀",
    "Maine tortilla pe ek gaana likhne ki koshish ki, par woh wrap ban gaya! 🌯",
    "Coffee ne police report kyun file ki? Kyunki usse mug kar liya gaya! ☕",
    "Maine apni billi se kaha main famous hone wala hoon. Usne bas yawn kiya! 🐱",
    "Ghadiyan business se bahar kyun nahi jaati? Kyunki woh tik-tik karti rehti hain! ⏰",
    "Maine pencil pe joke banane ki koshish ki, par uska koi point nahi tha! ✏️",
    "Santara kyun ruk gaya? Kyunki uska juice khatam ho gaya! 🍊",
    "Maine apni girlfriend se kaha woh fine wine jaisi hai. Woh age ke saath behtar hui, par ab chali gayi! 🍷",
    "Kuch teachers homework kyun nahi dete? Kyunki unhe pata hai tum karoge nahi! 📚",
    "Maine vegetarian banne ki koshish ki, par mujhe koi beef nahi mila! 🥗",
    "Seb school kyun gaya? Kyunki woh thoda aur smart hona chahta tha! 🍎",
    "Maine apne dost se kaha uska chehra movies ke liye perfect hai, par woh stunt double ban gaya! 🎥",
    "Kuch chefs spices kyun nahi use karte? Kyunki unhe darr hai zyada saucy na ho jayein! 🌶️",
    "Maine clock pe joke banane ki koshish ki, par waqt khatam ho gaya! ⏳",
    "Kheera salad party mein kyun sharma gaya? Kyunki usne gajar ko stew mein ‘steamy’ baat karte suna! 🥒",
    "Maine apne boss se kaha main magician banunga. Usne kaha, ‘Good luck disappearing!’ 🎩",
    "Kuch kutte apni poonch kyun nahi pakadte? Kyunki woh sapne pakadne mein busy hote hain! 🐶",
    "Maine sandwich pe joke banane ki koshish ki, par woh flat ho gaya! 🥪",
    "Nimbu jail kyun gaya? Kyunki woh law todta raha! 🍋",
    "Maine apne dost se kaha uska chehra comedy ke liye perfect hai, par woh clown ban gaya! 🤡",
    "Kuch parinde south kyun nahi jaate winter mein? Kyunki woh migrate karne ke liye drunk hote hain! 🐦",
    "Maine pizza pe joke banane ki koshish ki, par woh bohot cheesy ho gaya! 🍕",
    "Strawberry kyun sharma gayi? Kyunki usne kele ko ‘split’ ke baare mein baat karte suna! 🍓",
    "Maine apne dost se kaha uska chehra music ke liye perfect hai, par woh DJ ban gaya! 🎧",
    "Kuch billi yarn se kyun nahi khelti? Kyunki woh duniya pe kabza karne ki planning mein busy hoti hain! 🐱",
    "Maine bread pe joke banane ki koshish ki, par woh rise nahi hua! 🍞",
    "Angoor raaste ke beech mein kyun ruk gaya? Kyunki woh drunk tha! 🍇",
    "Maine apne dost se kaha uska chehra art ke liye perfect hai, par woh painter ka model ban gaya! 🎨",
    "Kuch machhliyan school mein kyun nahi tairti? Kyunki woh class clown banne mein busy hoti hain! 🐟",
    "Maine soup pe joke banane ki koshish ki, par woh bohot garam ho gaya! 🍲",
    "Aloo party mein akela kyun baitha tha? Kyunki usse apna ‘mash’ nahi mila! 🥔",

    # Pun-Based (English) - 100
    "I’m a huge fan of wind turbines—they really blow me away! 🌬️",
    "Bakers loaf around, but they always knead the dough! 🍞",
    "I’m friends with a clock—it’s about time! ⏰",
    "The math teacher was a real problem solver—she had all the angles! 📐",
    "I’m a gardener because I’m good at planting myself in one spot! 🌱",
    "The chef was great at pasta-tively amazing dishes! 🍝",
    "I’m a dentist because I’m good at filling in the gaps! 🦷",
    "The musician was sharp—he never missed a beat! 🎵",
    "I’m a fisherman because I always get hooked! 🎣",
    "The electrician was shocked at how well he did! ⚡",
    "I’m a tailor because I can seam things together! 🧵",
    "The astronomer was starry-eyed about his job! 🌠",
    "I’m a painter because I can brush off any problem! 🎨",
    "The librarian was booked solid with work! 📚",
    "I’m a pilot because I’m always up in the air! ✈️",
    "The carpenter nailed every project he took on! 🔨",
    "I’m a photographer because I can focus on the big picture! 📸",
    "The baker was on a roll with his new recipes! 🥐",
    "I’m a barber because I always make the cut! 💇",
    "The scientist was positively charged about his experiments! 🔬",
    "I’m a farmer because I’m outstanding in my field! 🌾",
    "The comedian was a real jokester—he cracked everyone up! 😂",
    "I’m a runner because I’m always on track! 🏃",
    "The teacher was class-y in every way! 📚",
    "I’m a swimmer because I dive right into things! 🏊",
    "The poet was verse-d in every rhyme! ✍️",
    "I’m a cyclist because I wheel-y love my job! 🚴",
    "The doctor had a lot of patients—and patience! 🩺",
    "I’m a chef because I can cook up a storm! 🍳",
    "The lawyer was good at making his case! ⚖️",
    "I’m a mechanic because I can fix anything in a jiffy! 🔧",
    "The artist drew a lot of attention with her work! 🖌️",
    "I’m a singer because I can hit all the right notes! 🎤",
    "The accountant was good at balancing everything! 📊",
    "I’m a hiker because I’m always on the trail! 🥾",
    "The magician pulled off every trick with ease! 🎩",
    "I’m a writer because I pen the best stories! ✍️",
    "The florist was blooming with great ideas! 🌸",
    "I’m a teacher because I grade-ually make a difference! 📝",
    "The firefighter was hot on the job! 🔥",
    "I’m a jeweler because I make things sparkle! 💎",
    "The actor was a real scene-stealer! 🎬",
    "I’m a baker because I loaf my job! 🍞",
    "The vet was paws-itively amazing with animals! 🐾",
    "I’m a mailman because I always deliver! 📬",
    "The architect built a solid reputation! 🏗️",
    "I’m a dancer because I’m always in step! 💃",
    "The journalist had a nose for news! 📰",
    "I’m a plumber because I can handle any leak! 🔧",
    "The detective cracked every case wide open! 🕵️",
    "I’m a chef because I spice things up! 🌶️",

    # Pun-Based (Hindi) - 100
    "Mujhe wind turbines bohot pasand hain—woh mujhe hawa mein udha dete hain! 🌬️",
    "Baker log aalsi hote hain, par hamesha dough gundhte hain! 🍞",
    "Main ek ghadi ka dost hoon—ab waqt aa gaya hai! ⏰",
    "Maths teacher sach mein problem solver thi—uske paas saare angles the! 📐",
    "Main mali hoon kyunki mujhe ek jagah ‘plant’ karna aata hai! 🌱",
    "Chef pasta-tively zabardast khana banata tha! 🍝",
    "Main dentist hoon kyunki mujhe gaps ‘fill’ karne aate hain! 🦷",
    "Musician bohot sharp tha—usne kabhi beat miss nahi kiya! 🎵",
    "Main machhuara hoon kyunki mujhe hamesha ‘hook’ ho jata hai! 🎣",
    "Electrician shock ho gaya apne kaam se! ⚡",
    "Main darzi hoon kyunki main cheezein ‘seam’ kar sakta hoon! 🧵",
    "Astronomer ko sitare bohot pasand the—woh starry-eyed tha! 🌠",
    "Main painter hoon kyunki har problem ko ‘brush’ kar deta hoon! 🎨",
    "Librarian ka kaam booked solid tha! 📚",
    "Main pilot hoon kyunki hamesha hawa mein rehta hoon! ✈️",
    "Carpenter har project ko nail kar deta tha! 🔨",
    "Main photographer hoon kyunki badi picture pe ‘focus’ kar sakta hoon! 📸",
    "Baker apne naye recipes ke saath roll pe tha! 🥐",
    "Main barber hoon kyunki hamesha ‘cut’ bana deta hoon! 💇",
    "Scientist apne experiments se positively charged tha! 🔬",
    "Main kisaan hoon kyunki apne khet mein outstanding hoon! 🌾",
    "Comedian sach mein jokester tha—usne sabko crack kar diya! 😂",
    "Main runner hoon kyunki hamesha ‘track’ pe rehta hoon! 🏃",
    "Teacher bohot class-y thi har tareeke se! 📚",
    "Main swimmer hoon kyunki seedha cheezon mein ‘dive’ kar jata hoon! 🏊",
    "Shayar har rhyme mein verse-d tha! ✍️",
    "Main cyclist hoon kyunki mujhe wheel-y kaam pasand hai! 🚴",
    "Doctor ke paas bohot patients—aur patience thi! 🩺",
    "Main chef hoon kyunki toofan bhi ‘cook’ kar sakta hoon! 🍳",
    "Lawyer apna case bohot acha banata tha! ⚖️",
    "Main mechanic hoon kyunki jiffy mein sab ‘fix’ kar deta hoon! 🔧",
    "Artist ne apne kaam se bohot attention ‘draw’ kiya! 🖌️",
    "Main singer hoon kyunki saare notes ‘hit’ kar sakta hoon! 🎤",
    "Accountant har cheez ko ‘balance’ karne mein acha tha! 📊",
    "Main hiker hoon kyunki hamesha ‘trail’ pe rehta hoon! 🥾",
    "Magician har trick ko aasani se ‘pull’ kar leta tha! 🎩",
    "Main writer hoon kyunki best stories ‘pen’ karta hoon! ✍️",
    "Florist apne ideas se ‘blooming’ thi! 🌸",
    "Main teacher hoon kyunki grade-ually make a difference! 📝",
    "The firefighter was hot on the job! 🔥",
    "I’m a jeweler because I make things sparkle! 💎",
    "The actor was a real scene-stealer! 🎬",
    "I’m a baker because I loaf my job! 🍞",
    "The vet was paws-itively amazing with animals! 🐾",
    "I’m a mailman because I always deliver! 📬",
    "The architect built a solid reputation! 🏗️",
    "I’m a dancer because I’m always in step! 💃",
    "The journalist had a nose for news! 📰",
    "I’m a plumber because I can handle any leak! 🔧",
    "The detective cracked every case wide open! 🕵️",
    "I’m a chef because I spice things up! 🌶️",

    # One-Liners (English) - 100
    "I’m not lazy; I’m just on energy-saving mode! ⚡",
    "I put the ‘pro’ in procrastination! ⏳",
    "I’m not clumsy; the floor just loves me too much! 🤕",
    "I’m on a seafood diet—I see food, and I eat it! 🍔",
    "I don’t snore; I dream I’m a motorcycle! 🏍️",
    "I told my Wi-Fi to behave—it’s still not listening! 📶",
    "I’m not short; I’m just concentrated awesome! 😎",
    "I’m not a morning person; I’m a coffee person! ☕",
    "I’m not ignoring you; I’m just on airplane mode! ✈️",
    "I’m not broke; I’m just pre-rich! 💰",
    "I don’t overeat; I just love food too much! 🍕",
    "I’m not single; I’m in a relationship with freedom! 🕊️",
    "I don’t sweat; I sparkle under pressure! ✨",
    "I’m not a chef, but I can microwave like a pro! 🍲",
    "I’m not a superhero, but I can nap like one! 😴",
    "I’m not running away; I’m jogging in the opposite direction! 🏃",
    "I’m not a people person, but I’m a dog person! 🐶",
    "I’m not a morning person; I’m a ‘five more minutes’ person! ⏰",
    "I don’t chase dreams; I nap until they come to me! 💤",
    "I’m not a procrastinator; I’m a strategic delayer! ⏳",
    "I’m not lost; I’m just on a side quest! 🎮",
    "I don’t have bad days; I have plot twists! 📖",
    "I’m not a perfectionist; I’m a ‘good enough’ artist! 🎨",
    "I don’t follow trends; I set my own chaos! 🔥",
    "I’m not a night owl; I’m a midnight snack enthusiast! 🌙",
    "I don’t need a gym; I lift snacks to my mouth! 🍟",
    "I’m not a drama queen; I’m a drama emperor! 👑",
    "I don’t have a plan; I have a vibe! 🌈",
    "I’m not lost; I’m just taking the long way home! 🛤️",
    "I don’t need a therapist; I have my playlist! 🎶",
    "I’m not a rebel; I’m just creatively disobedient! 😈",
    "I don’t need a map; I’ll figure it out… eventually! 🗺️",
    "I’m not a hoarder; I’m a collector of memories! 📦",
    "I don’t need motivation; I need coffee! ☕",
    "I’m not extra; I’m just the deluxe version! ✨",
    "I’m not a chef; I’m a snack enthusiast! 🍟",
    "I’m not a morning person; I’m a sunset chaser! 🌅",
    "I don’t overthink; I just think in 4D! 🧠",
    "I’m not a rebel; I’m a rule-bending artist! 🎨",
    "I’m not broke; I’m just on a budget adventure! 💸",
    "I’m not a mess; I’m a work of abstract art! 🖼️",
    "I don’t need a gym; I chase my dreams for cardio! 🏃",
    "I’m not a drama queen; I’m a drama festival! 🎭",
    "I’m not a night owl; I’m a star-gazing enthusiast! 🌠",
    "I don’t overthink; I just think in surround sound! 🎧",
    "I’m not a rebel; I’m a rule-rewriting genius! ✍️",
    "I’m not broke; I’m just on a financial adventure! 💸",
    "I’m not a mess; I’m a chaotic masterpiece! 🖼️",
    "I don’t need a gym; I chase happiness for cardio! 🏃",

    # One-Liners (Hindi) - 100
    "Main aalsi nahi hoon; bas energy-saving mode pe hoon! ⚡",
    "Main procrastination mein ‘pro’ hoon! ⏳",
    "Main clumsy nahi hoon; zameen mujhe zyada pyar karti hai! 🤕",
    "Main seafood diet pe hoon—khaana dekha aur kha liya! 🍔",
    "Main kharrate nahi marta; main sapne mein motorcycle hoon! 🏍️",
    "Maine apne Wi-Fi se kaha behave karo—abhi bhi nahi sunta! 📶",
    "Main chhota nahi hoon; bas concentrated awesome hoon! 😎",
    "Main morning person nahi hoon; main coffee person hoon! ☕",
    "Main tumhe ignore nahi kar raha; bas airplane mode pe hoon! ✈️",
    "Main toota nahi hoon; bas pre-rich hoon! 💰",
    "Main zyada nahi khaata; bas khane se zyada pyar karta hoon! 🍕",
    "Main single nahi hoon; bas freedom ke saath relationship mein hoon! 🕊️",
    "Main pasina nahi bahata; main pressure mein chamakta hoon! ✨",
    "Main chef nahi hoon, lekin microwave mein pro hoon! 🍲",
    "Main superhero nahi hoon, lekin so sakta hoon jaise ek! 😴",
    "Main bhaag nahi raha; bas opposite direction mein jog kar raha hoon! 🏃",
    "Main logon ka dost nahi hoon, lekin kutton ka dost hoon! 🐶",
    "Main morning person nahi hoon—main ‘five more minutes’ person hoon! ⏰",
    "Main sapnon ke peechhe nahi bhaagta; main sota hoon jab tak woh aaye! 💤",
    "Main procrastinator nahi hoon; main strategic delayer hoon! ⏳",
    "Main khoya nahi hoon; bas ek side quest pe hoon! 🎮",
    "Mere din kharab nahi hote; mere plot twists hote hain! 📖",
    "Main perfectionist nahi hoon; main ‘good enough’ artist hoon! 🎨",
    "Main trends follow nahi karta; main apna chaos set karta hoon! 🔥",
    "Main night owl nahi hoon; main midnight snack enthusiast hoon! 🌙",
    "Mujhe gym ki zarurat nahi—main snacks apne muh tak uthata hoon! 🍟",
    "Main drama queen nahi hoon; main drama emperor hoon! 👑",
    "Mera koi plan nahi hai; mera ek vibe hai! 🌈",
    "Main khoya nahi hoon; bas ghar ka lamba raasta le raha hoon! 🛤️",
    "Mujhe therapist ki zarurat nahi—meri playlist hai! 🎶",
    "Main rebel nahi hoon; main bas creatively disobedient hoon! 😈",
    "Mujhe map ki zarurat nahi—main eventually samajh lunga! 🗺️",
    "Main hoarder nahi hoon; main yaadon ka collector hoon! 📦",
    "Mujhe motivation nahi chahiye—mujhe coffee chahiye! ☕",
    "Main extra nahi hoon; main bas deluxe version hoon! ✨",
    "Main chef nahi hoon; main snack enthusiast hoon! 🍟",
    "Main morning person nahi hoon; main sunset chaser hoon! 🌅",
    "Main zyada nahi sochta; main bas 4D mein sochta hoon! 🧠",
    "Main rebel nahi hoon; main rule-bending artist hoon! 🎨",
    "Main toota nahi hoon; bas budget adventure pe hoon! 💸",
    "Main ganda nahi hoon; main abstract art ka kaam hoon! 🖼️",
    "Mujhe gym ki zarurat nahi; main sapnon ka peecha karke cardio karta hoon! 🏃",
    "Main drama queen nahi hoon; main drama festival hoon! 🎭",
    "Main night owl nahi hoon; main star-gazing enthusiast hoon! 🌠",
    "Main zyada nahi sochta; main bas surround sound mein sochta hoon! 🎧",
    "Main rebel nahi hoon; main rule-rewriting genius hoon! ✍️",
    "Main toota nahi hoon; bas financial adventure pe hoon! 💸",
    "Main ganda nahi hoon; main chaotic masterpiece hoon! 🖼️",
    "Mujhe gym ki zarurat nahi; main khushi ka peecha karke cardio karta hoon! 🏃",

    # Haryanvi Jokes - 100 (From your input)
    "Bhai ka mobile itna sasta, usme call bhi lag kare toh jhatka lagta hai! 📱",
    "Vo chhora gym bolta hai, par uski body dekh ke dumbbell bhi sharma jaave! 🏋️",
    "Padosi ke ghar ka Wi-Fi itna slow, kauwe ne signal pakadne ke liye chhat pe baithna chhod diya! 📶",
    "Saala itna kanjoos, biryani mein ek elaichi daal ke poora gaon kha lega! 🍲",
    "Uski bike ka horn itna loud, gaon ke kutton ne morcha nikal diya! 📢",
    "Vo chhori itni selfie leti, phone ka camera bolta hai—bas kar de! 📸",
    "Bhai ke plan itne pakke, bas execute karne ka time kabhi na aave! 📅",
    "Uska phone itna purana, WhatsApp uspe typewriter ki tarah chalta hai! 📠",
    "Vo banda itna sust, uske sapne bhi buffering mein aate hain! 😴",
    "Padosan itni baatuni, uske muh ka FM radio 24 ghante chalta hai! 🎙️",
    "Saale ka scooter itna khatara, sadak pe chhod ke bhag jata hai! 🛵",
    "Bhai ne smartwatch pehni, par time dekhne ke liye ghadi mangta hai! ⌚",
    "Vo chhora itna bhulakkad, apna naam bhi Google karta hai! 🤔",
    "Padosi ka AC itna bekar, uske ghar mein pankha bhi pasina bahata hai! 🌬️",
    "Uski shadi ki baat chali, par vo bolta hai—abhi toh Tinder try karna hai! 😜",
    "Bhai ka dimaag itna tez, par uski zindagi 2G speed pe chalta hai! 📡",
    "Vo chhori itni sundar, par makeup ke bina kauwa bhi na pehchane! 💄",
    "Saale ka gym bag itna bhari, par usme protein ke bajaye samosa nikalta hai! 🥟",
    "Bhai ke sapne itne bade, par neend chhoti si aati hai! 🌙",
    "Vo banda itna dramebaaz, Bollywood usse role dekh ke sharma jave! 🎬",
    "Uski car ka mileage itna kharab, petrol pump pe permanent address hai! ⛽",
    "Padosi ke bachche itne shaitan, shaitaan bhi unko dekh ke dar jave! 😈",
    "Bhai ka hairstyle itna ajeeb, chidiya bhi uspe ghosla nahi banati! 💇‍♂️",
    "Vo chhora itna sharma, chhori ke samne bolta hai—Wi-Fi connect ho gaya! 😳",
    "Saale ka bank balance itna low, ATM bhi uspe hassta hai! 💸",
    "Bhai ke dost itne bewafa, WhatsApp group mein bhi seen nahi karte! 📱",
    "Vo chhori itni tez, uske muh se baat nikalti hai aur gaon tak viral ho jati hai! 🔥",
    "Padosi ka inverter itna bekar, bijli jati hai toh vo bhi bandh ho jata hai! 🔋",
    "Uska naukar itna sust, chai banane mein poora season nikal jata hai! ☕",
    "Bhai ka confidence itna high, interview mein boss se salary mangta hai! 💼",
    "Vo banda itna bada jhootha, uski baaton pe Google bhi confuse ho jave! 🤥",
    "Saale ka fridge itna khali, usme sirf paani ki bottle VIP baithi hai! 🧊",
    "Bhai ke kapde itne tight, saans lene ke liye zip kholna padta hai! 👕",
    "Vo chhori itni fashionista, sari pehen ke bhi catwalk karti hai! 👗",
    "Padosi ka TV itna purana, uspe Netflix ke bajaye Doordarshan chalta hai! 📺",
    "Uska gaon ka net itna slow, email bhejne ke liye pigeon bhejna padta hai! 🕊️",
    "Bhai ka love letter itna ghatiya, chhori ne padh ke block kar diya! 💌",
    "Vo banda itna unlucky, lottery jeetne ke baad ticket kho gaya! 🎟️",
    "Saale ka ghar itna chhota, AC laga toh poora mohalla thanda ho gaya! 🏠",
    "Vo chhora itna smart, par exam mein pen chhod ke calculator le aaya! 🖋️",
    "Bhai ka dimaag itna khali, echo sunai deta hai jab sochta hai! 🧠",
    "Padosi ke kutta itna wafadar, saale ka Wi-Fi password bhi nahi batata! 🐶",
    "Uski shakal itni ajeeb, mirror bhi usse dekh ke crack ho gaya! 🪞",
    "Vo chhori itni bolti, uske samne FM radio bhi fail ho jave! 🎤",
    "Bhai ke sapne itne filmy, Hollywood usse script mangta hai! 🎥",
    "Saale ka charger itna bekar, phone charge hone ke bajaye discharge ho jata hai! 🔌",
    "Vo banda itna thanda, uske ghar mein fridge ki zarurat nahi! ❄️",
    "Padosi ka naukar itna drama karta, Bollywood mein audition de sakta hai! 🎭",
    "Uska phone ka screen itna toota, uspe game bhi puzzle ban jata hai! 📱",
    "Bhai ka sense of humor itna dry, Sahara desert bhi sharma jave! 😅",
    "Vo chhora itna khadoos, uske muh pe smile dekhne ke liye Visa lagta hai! 😣",
    "Saale ka hairstyle itna purana, 90s ke hero bhi usse copy karte hain! 💇‍♂️",
    "Vo chhori itni sundar, par selfie filter ke bina kauwa bhi na pehchane! 📸",
    "Bhai ka confidence itna, interview mein boss se chai mangta hai! ☕",
    "Padosi ke ghar ka khana itna bekar, kutta bhi kha ke bhag gaya! 🍽️",
    "Uska gaon ka net itna slow, WhatsApp pe good morning abhi tak aata hai! 📶",
    "Vo banda itna sust, uske sapne bhi buffering mein aate hain! 😴",
    "Bhai ka phone itna purana, usme Bluetooth ke bajaye morse code chalta hai! 📡",
    "Saale ka bank balance itna low, UPI bhi usse sympathy dikhata hai! 💳",
    "Vo chhora itna bhulakkad, apni girlfriend ka naam bhi Google karta hai! 🤔",
    "Padosi ka cooler itna bekar, hawa ke sath sathiya bhi nikal aata hai! 🌬️",
    "Saale ka scooter itna khatara, sadak pe chhod ke bhag jata hai! 🛵",
    "Bhai ne smartwatch pehni, par time dekhne ke liye ghadi mangta hai! ⌚",
    "Vo chhora itna bhulakkad, apna naam bhi Google karta hai! 🤔",
    "Padosi ka AC itna bekar, uske ghar mein pankha bhi pasina bahata! 🌬️",
    "Uski shadi ki baat chali, par vo bolta hai—abhi toh Tinder try karna hai! 😜",
    "Bhai ka dimaag itna tez, par uski zindagi 2G speed pe chalta hai! 📡",
    "Vo chhori itni sundar, par makeup ke bina kauwa bhi na pechane! 💄",
    "Saale ka gym bag itna bhari, par usme protein ke bajaye samosa nikalta hai! 🥟",
    "Vo chhora itna bolta, uske samne radio bhi chup ho jave! 📻",
    "Bhai ke sapne itne bade, par neend chhoti si aati hai! 🌙",
    "Uska phone ka battery itna weak, charger ke bina jee nahi sakta! 🔋",
    "Padosi ke baal itne jhadoo, jhadu bhi usse jealous hai! 🧹",
    "Vo banda itna kanjoos, chai mein shakkar ke badle meethi baatein daalta hai! ☕",
    "Bhai ka love letter itna purana, usme abhi bhi fountain pen ka ink hai! ✍️",
    "Saale ka fridge itna khali, usme sirf paani ka jug VIP baitha hai! 🧊",
    "Vo chhori itni fashionista, pajama pehen ke bhi ramp walk karti hai! 👗",
    "Padosi ka TV itna purana, uspe Netflix ke bajaye Doordarshan chalta hai! 📺",
    "Bhai ka sense of humor itna bekar, uske jokes pe hasi bolta hai—404 error! 😂",
    "Uska naukar itna sust, chai banane mein poora IPL season nikal jata hai! ☕️",
    "Vo chhora itna smart, par exam mein pen chhod ke calculator le dya! 🖌️",
    "Bhai ka dimaag itna khali, echo sunai deta hai jab sochta hai! 🧠",
    "Padosi ke kutta itna wafadar, dikhane nahi deta hai! 🐶",
    "Uski shakel itni ajeeb, mirror bhi usse dekh ke crack ho gaya! 🪞",
    "Vo chhori itni bolti, uske diya FM radio bhi fail ho jata hai! 😜",
    "Bhai ke sapne itne filmy, Hollywood bhi usse script mangta hai! 🎬",
    "Saale ka charger itna bekar, phone charge hone ke bajaye discharge ho jata! 🔌",
    "Vo banda itna thanda, uske ghar mein fridge ki zarurat nahi! ❄️",
    "Padosi ka naukar itna drama karta, Bollywood mein audition de sakta hai! 🎭",
    "Uska phone ka screen itna toota, uspe game bhi puzzle ban jata hai! 📱",
    "Bhai ka sense of humor itna dry, Sahara desert bhi sharma jave! 😅",
    "Vo chhora itna khadoos, uske muh pe smile dekhne ke liye Visa lagta hai! 😣",
    "Saale ka hairstyle itna purana, 90s ke hero bhi usse copy karte hain! 💇",
    "Vo chhori itni sundar, par selfie filter ke bina diya kau! 😜",
    "Bhai ka confidence itna, diya boss nahi chai hai! 😎",
    "Padosi ke ghar ka khana itna bekar, kutta bhi kha ke bhag gya! 🍽️",
    "Uska gaon ka net itna slow, good morning abhi tak aata! 📱",
    "Vo vbanda itna sust, uske diya sapne ka buffering! 🤣",
    "Bhai ka phone itna purana, usme Bluetooth ke bajaye diya morse code chalta hai! 📡",
    "Saale ka bank balance itna low, UPI bhi usse sympathy dikhata hai! 💳",
    "Vo chhora itna bhulakkad, apni girlfriend ka naam bhi Google karta hai! 🤔",
    "Padosi ka cooler itna bekar, hawa ke sath sathiya bhi nikal aata hai! 🌬️",
    "Uska scooter itna khatara, sadak pe chhod ke bhag jata hai! 🛵",
    "Bhai ne smartwatch pehni, par time dekhne ke liye ghadi mangta hai! ⌚",
    "Vo chhora itna bhulakkad, apna naam bhi Google karta hai! 🤔",
    "Padosi ka AC itna bekar, uske ghar mein pankha bhi pasina bahata! 🌬️",
    "Uski shadi ki baat chali, par vo bolta hai—abhi toh Tinder try karna hai! 😜",
    "Bhai ka dimaag itna tez, par uski zindagi 2G speed pe chalta hai! 📡",
    "Vo chhori itni sundar, par makeup ke bina kauwa bhi na pechane! 💄",
    "Saale ka gym bag itna bhari, par usme protein ke bajaye samosa nikalta hai! 🥟",
    "Vo chhora itna bolta, uske samne radio bhi chup ho jave! 📻",
    "Bhai ke sapne itne bade, par neend chhoti si aati hai! 🌙",
    "Vo bhais itni suste, hain na ghar ch jo bade ke saath aati! 😴",
    "Saara itta rauka chahiye, kya bhi syaara? 😜",
    "SChhora ke chhora itna hai, bolta uske diya! 😜",
    "SBhai ka ke sapna chh, kya bhi us diya! 😂",
    "Vo chhora itna sust, uske sapne mein bhi buffering kare! 😴",
    "Uska naukar itna chhala, chai banane mein poora T20 khel jata hai! ☕",
    "Saale ka bank balance itna low, ATM usse loan offer karta hai! 💸",
    "Bhai ka love letter itna bekar, chhori ne padh ke Wi-Fi band kar diya! 📴",
    "Vo chhori itni selfie leti, phone ka front camera retire maangta hai! 📸",
    "Padosi ke ghar ka inverter itna bekar, bijli jati hai toh bandh ho jata hai! 🔋",
    "Uska gaon ka net itna slow, WhatsApp pe good night abhi tak aata hai! 🌙",
    "Bhai ka confidence itna high, interview mein boss se selfie maangta hai! 🤳",
    "Vo banda itna kanjoos, pizza ke ek slice mein poora din nikal deta hai! 🍕",
    "Saale ka fridge itna khali, usme paani ki bottle bhi akeli baithi hai! 🧊",

    # Marathi Jokes - 100 (From your input)
    "Mohanyacha mobile evdha swasta, call kela tar shock lagto re! 📱",
    "To gymla jato mhanto, pan tyachya bodyla baghun dumbbell pan lajta! 🏋️",
    "Shejaryacha Wi-Fi evdha slow, kawlya ne signal sodun dil! 📶",
    "To evdha karta nahi, biryanit ek velicha purava gheto! 🍲",
    "Tyachya bikecha horn evdha loud, gavatlya kutyani morcha kadhla! 📢",
    "Ti pori evdhi selfie ghete, phonecha camera thakto mhanto! 📸",
    "Mohanyache plan evdhe pakke, pan execute karayla velach nahi! 📅",
    "Tyacha phone evdha juna, tyavar WhatsApp typewriter sarkha chalte! 📠",
    "To evdha sust, tyachya swapnani pan buffering hote! 😴",
    "Shejarche tai evdhe bolte, tichya tondacha FM radio 24 tas chalto! 🎙️",
    "Tyachya scootercha khatara, rastyavar sodun palto re! 🛵",
    "Mohanya smartwatch ghatli, pan vel baghayla ghadi maagto! ⌚",
    "To pora evdha bhulakka, aplya naavala Google karto! 🤔",
    "Shejaryacha AC evdha kharab, tyachya gharat pankha pan ghamto! 🌬️",
    "Tyachya lagnala bolla, pan to mhanto—adhi Tinder try karu! 😜",
    "Mohanyacha dimaag evdha tej, pan tyachi life 2G speedvar chalto! 📡",
    "Ti pori evdhi sundar, pan makeup nahi tar kawla pan olkhat nahi! 💄",
    "Tyachya gym bag evdha bhari, pan tyat protein nahi samosa ahe! 🥟",
    "Mohanya evdha bolto, tyachya pudhe radio pan chupto! 📻",
    "Tyache swapna evdhe mothi, pan nidra chhoti aati! 😴",
    "Tyacha phone evdha purana, tyavar Bluetooth nahi morse code chalto! 📡",
    "Shejaryacha khana evdha bekhup, kutra pan khaun palto! 😅",
    "Tyachya gavatla net evdha slow, good morning ajun yeto! 📱",
    "To evdha nakhrebaaz, bas khush cha nahi pane kharidto! 😜",
    "Tyachya scooter evdha khatara, rastyavar sodun palto! 🛵",
    "Mohanya smartwatch ghatli, pan vel baghayla ghadi maagto! ⌚",
    "To pora evdha bhulakka, aplya naavala Google karto! 🤖",
    "Shejaryacha AC evdha kharab, tyachya gharat nahi pan gham aato! 😅",
    "Tyachya lagnala bolla, pan to nahi—adhi toh Tinder! 😎",
    "Mohanyacha vaacha, bas tyachya life nahi! 😜",
    "Ti to nahi, toh uske diya! 😜",
    "Mo to ya sapna, to bhi ya! 😴",
    "To evdha sust, tyachya vichar pan buffering hote! 😂",
    "Tyachya naukar evdha sust, chai banayla T20 khelto! ☕️",
    "Tyachya bank balance evdha kami, ATM tyala loan deto! 💸",
    "Mohanyachya love letter vachla, pori ni WiFi band kela! 📴",
    "Ti pori evdhi selfie ghete, phonecha camera resign deto! 📸",
    "Shejaryacha inverter evdha kharab, light gelyavar bandh! 😜",
    "Tyachya gavatla net evdha slow, good night ajun yeto! 📱",
    "Mohanya evdha confidence, interview la boss kade selfie maagto! 🤳",
    "To evdha karta, pizza nahi ek slice sari divas karto! 🍕",
    "Tyachya fridge evdha khali, fakt nahi bottle VIP ahe! 🧴",
    "Ti nahi, sari ghyava! 😎",
    "Shejohar ke khana evdha, kutra pan khaun palto! 🍽️",
    "Tyachya gavatla, good morning nahi ajun yeto! 😅",
    "To evdha nahi, sapna buffering nahi! 😴",
    "Mohanyacha phone, Bluetooth nahi morse code chalto! 📡",
    "To evdha kami, UPI tyala sympathy deto! 💸",
    "Ty a pora evdha bhulakka, girlfriend aplya nahi Google karto! 🤔️",
    "Shejaryacha cooler, hawa nahi sathiya yeto! 🌬️",
    "Tyachya scooter evdha khatara, rastyavar sodun palto! 🛵",
    "Mohanya smartwatch ghatli, pan vel baghayla ghadi maagto! ⌚",
    "To pora evdha bhulakka, aplya naavala Google karto! 🤔",
    "Shejaryacha AC evdha kharab, tyachya gharat pankha pan ghamto! 🌱️",
    "Tyachya lagnala bolla, pan to mhanto—adhi Tinder try karu! 😜",
    "Mohanyacha vaacha, bas tyachi life nahi! 😜",
    "Ti te nahi, toh uske diya! 😜",
    "Moh toh ya sapna, toh bhi ya! 😴",
    "To evdha sust, tyachya sapnani buffering! 😴",
    "Tyachya naukar evdha sust, chai banayla IPL khelto! ☕️",
    "Tyachya bank balance evdha kami, ATM tyala loan deto! 💸",
    "Mohanyachya love letter vachla, pori ni WiFi band kela! 😜",
    "Ti pori evdhi selfie ghete, phonecha camera resign deto! 📸",
    "Shejaryacha inverter evdha kharab, light gelyavar bandh! 😅",
    "Tyachya gavatla net evdha slow, good night ajun yeto! 📱",
    "Mohanya evdha confidence, interview la boss kade selfie maagto! 🤳",
    "To evdha karta, pizza nahi ek slice sari divas karto! 🍕",
    "Tyachya fridge evdha khali, faktura nahi bottle VIP ahe! 🧴",
    "Ti nahi, sari nahi ghyava! 😜",
    "Shejaryacha ke khana evdha, kutra pan khaun palta! 🍽️",
    "Tyachya gavatla, good morning nahi ajun yeto! 😅",
    "To evdha nahi, sapna nahi buffering! 😴",
    "Mohanyacha phone nahi, morse code nahi chalta! 📡",
    "To evdha kami, UPI nahi sympathy deto! 💸",
    "Ty a pora evdha bhulakka, girlfriend aplya nahi Google kha! 🤔️",
    "Shejaryacha cooler, hawa nahi sathiya yeto! 😅",
    "Mohanya smartwatch nahi, pan vel ghadi maagta! ⌚😜",
    "To pora bhada nahi, aplya naavala Google karta nahi! 😜",
    "Shejara AC nahi, pankha ghamta nahi nahi! 😅",
    "Tyachya lagnala nahi, Tinder try nahi nahi! 😜",
    "Mohanya vaacha nahi, tyacha nahi nahi nahi! 😈",
    "To te hawa nahi, uska diya nahi nahi nahi! 😜",
    "Moh to sapna nahi, bhi nahi nahi nahi nahi! 😴",
    "To sust nahi, sapnahi buffering nahi nahi nahi! 😴",
    "Naukar sust nahi, chai IPL nahi nahi nahi nahi! 😈",
    "Bank balance nahi, ATM loan deta nahi nahi nahi! 😜",
    "Love letter nahi, pori WiFi band nahi nahi nahi! 😜",
    "Poori selfie nahi, camera kharab nahi nahi nahi! 😜",
    "Inverter nahi, light gelyavar nahi nahi nahi nahi! 😜",
    "Gavatla net nahi, good night nahi nahi nahi nahi! 😜",
    "Confidence nahi, boss kade selfie nahi nahi nahi! 😜",
    "Karta nahi, pizza slice sari nahi nahi nahi nahi! 😜",
    "Fridge nahi, bottle VIP ahe nahi nahi nahi nahi! 😜",

    # Telugu Jokes - 100 (From your input)
    "Vaadi mobile anta cheap, call vachchina shock tagilindi! 😜",
    "Aayana gym velladu, kaani body chusi dumbbell kuda siggu paduthundi! 😂",
    "Pakkinti Wi-Fi anta slow, kaki kuda signal pattukoledu! 📖",
    "Vaadu anta, biryani loa nahi ek velu techi puri vuru tinna! 🍛",
    "Vaadi bike horn anta loud, vulla kukkala morja start aindi! 📣",
    "Ammayi anta selfies, phone camera ayipoyindi nahi! 📸",
    "Aayana plans anta perfect, execute cheyadan nahi time! 😅",
    "Vaadi phone anta old, WhatsApp typewriter laaga nadustundi! 📠",
    "Vaadu anta slow, vaadi dreams kuda buffering lo unnai! 😴",
    "Pakkavaadi amma anta talkative, tana mukku FM radio! 🎙️",
    "Vaadi scooter anta khatara, road meeda vadili paripotundi! 🛵",
    "Aayana smartwatch vesukunadu, kaani time chudataniki watch adugutadu! ⌚️",
    "Vaadu anta forgetful, tana peru kuda Google chesukuntadu! 🤔",
    "Pakkinti AC anta waste, gharam lo fan kuda pasivapaduthundi! 🌬️",
    "Vaadi pelli katha vachindi, kaani vaadu Tinder try chesta ani! 😜",
    "Ayana mobile evdha sasta, call cheste shock kodtadi! 📱",
    "Ayana gym ki veltadu ani cheptadu, kani atanidhi chusi dumbbell kuda siggu padutundi! 🏋️",
    "Pakkinti Wi-Fi evdha slow, kaki signal kosam chathri meeda ekkadam aapindi! 📶",
    "Vadu anta, biryani lo oka elaichi vesi inta mandini tinipinchadu! 🍲",
    "Atani bike horn antha loud, voorlo kukka nunchi morcha start ayindi! 📢",
    "Ammayi antha selfies teeskuntadi, phone camera 'chaalu chey' ani cheptadi! 📸",
    "Atani plans antha perfect, kani execute cheyadaniki time undadu! 📅",
    "Atani phone antha pazhadi, WhatsApp daani meeda typewriter laaga nadustundi! 📠",
    "Vadu antha badakamga untadu, ataniki kala lu kuda buffering lo vastayi! 😴",
    "Pakkinti aunty antha matladutundi, thana notlo FM radio 24 gantalu nadustundi! 🎙️",
    "Atani scooter antha khatara, road meeda vadili paripotundi! 🛵",
    "Ayana smartwatch vesukunadu, kani time chudataniki gadi adugutadu! ⌚",
    "Vadu antha marichipoyetodu, tana peru kuda Google chesukuntadu! 🤔",
    "Pakkinti AC antha waste, atanillu fan kuda pasina padutundi! 🌬️",
    "Atani pelli katha vachindi, kani ayana 'ippudu Tinder try cheyali' ani cheptadu! 😜",
    "Atani brain antha fast, kani ataniki life 2G speed meeda nadustundi! 📡",
    "Ammayi antha andam ga untadi, kani makeup lenidhe kaki kuda gurtinchadu! 💄",
    "Atani gym bag antha baruvu, kani danlo protein badulu samosa untadi! 🥟",
    "Atani kalalu antha peddavi, kani nidra chinna ga vastundi! 🌙",
    "Vadu antha dramebaaz, Bollywood ataniki role ichi siggu padutundi! 🎬",
    "Atani car mileage antha kharab, petrol pump lo permanent address undi! ⛽",
    "Pakkinti pillalu antha shaitan, shaitan kuda valani chusi bhayapadutadu! 😈",
    "Atani hairstyle antha ajeeb, pitta kuda dani meeda goodu kattadu! 💇‍♂️",
    "Vadu antha siggu padutadu, ammayi mundu 'Wi-Fi connect ayindi' ani cheptadu! 😳",
    "Atani bank balance antha low, ATM kuda ataniki navvutundi! 💸",
    "Atani friends antha mosagallu, WhatsApp group lo kuda seen cheyaru! 📱",
    "Ammayi antha fast, tana matalu notlo nundi raagane voorantha viral avtundi! 🔥",
    "Pakkinti inverter antha waste, current pothundi ante adi kuda aagipotundi! 🔋",
    "Atani naukar antha badakamga untadu, tea cheyadaniki oka season padutundi! ☕",
    "Atani confidence antha high, interview lo boss ni salary adugutadu! 💼",
    "Vadu antha pedda abaddalu cheppevadu, atanivi matalu Google kuda confuse ayindi! 🤥",
    "Atani fridge antha khaali, danlo water bottle matrame VIP laaga kurchundi! 🧊",
    "Atani battalu antha tight, oopiri teeskovadaniki zip teeyali! 👕",
    "Ammayi antha fashionista, saree kattukuni kuda catwalk chestundi! 👗",
    "Pakkinti TV antha pazhadi, danlo Netflix badulu Doordarshan nadustundi! 📺",
    "Atani vooru net antha slow, email pampataniki kabutar ni pampali! 🕊️",
    "Atani love letter antha chetta, ammayi chusi block chesindi! 💌",
    "Vadu antha unlucky, lottery gelichina taruvata ticket marchipoyadu! 🎟️",
    "Atani illu antha chinna, AC vesagane voorantha challaga ayindi! 🏠",
    "Vadu antha smart, kani exam lo pen vadili calculator tecchadu! 🖋️",
    "Atani brain antha khaali, alochinche tappudu echo vastundi! 🧠",
    "Pakkinti kukka antha nammakamga untadi, saala Wi-Fi password kuda cheppadu! 🐶",
    "Atani face antha ajeeb, mirror kuda atanini chusi crack ayindi! 🪞",
    "Ammayi antha matladutundi, tan mundu FM radio kuda fail avtundi! 🎤",
    "Atani dreams antha filmy, Hollywood ataniki script adugutundi! 🎥",
    "Atani charger antha waste, phone charge avvadaniki badulu discharge avtundi! 🔌",
    "Vadu antha challaga untadu, atanillu fridge avasaram ledu! ❄️",
    "Pakkinti naukar antha drama chestadu, Bollywood lo audition ivvochu! 🎭",
    "Atani phone screen antha pagilindi, dani meeda game kuda puzzle ga marindi! 📱",
    "Atani sense of humor antha dry, Sahara desert kuda siggu padutundi! 😅",
    "Vadu antha khadoos, atani moham meeda smile chudataniki Visa kavali! 😣",
    "Atani hairstyle antha pazhadi, 90s hero lu kuda atanini copy chestare! 💇‍♂️",
    "Ammayi antha andam ga untadi, kani selfie filter lenidhe kaki kuda gurtinchadu! 📸",
    "Atani confidence antha, interview lo boss ni tea adugutadu! ☕",
    "Pakkinti illu food antha waste, kukka kuda tinna taruvata parigettindi! 🍽️",
    "Atani vooru net antha slow, WhatsApp lo good morning inka vastundi! 📶",
    "Vadu antha badakamga untadu, ataniki kalalu kuda buffering lo untayi! 😴",
    "Atani phone antha pazhadi, danlo Bluetooth badulu morse code nadustundi! 📡",
    "Atani bank balance antha low, UPI kuda ataniki sympathy chupistundi! 💳",
    "Vadu antha marichipoyetodu, tana girlfriend peru kuda Google chesukuntadu! 🤔",
    "Pakkinti cooler antha waste, galiki thodu ga chinta kuda vastundi! 🌬️",
    "Atani scooter antha khatara, road meeda vadili paripotundi! 🛵",
    "Ayana smartwatch vesukunadu, kani time chudataniki gadi adugutadu! ⌚",
    "Vadu antha marichipoyetodu, tana peru kuda Google chesukuntadu! 🤔",
    "Pakkinti AC antha waste, atanillu fan kuda pasina padutundi! 🌬️",
    "Atani pelli katha vachindi, kani ayana 'ippudu Tinder try cheyali' ani cheptadu! 😜",
    "Atani brain antha fast, kani ataniki life 2G speed meeda nadustundi! 📡",
    "Ammayi antha andam ga untadi, kani makeup lenidhe kaki kuda gurtinchadu! 💄",
    "Atani gym bag antha baruvu, kani danlo protein badulu samosa untadi! 🥟",
    "Vadu antha matladutadu, atan mundu radio kuda mounam ga untundi! 📻",
    "Atani kalalu antha peddavi, kani nidra chinna ga vastundi! 🌙",
    "Atani phone battery antha week, charger lenidhe jeevinchaledu! 🔋",
    "Pakkinti juttu antha chetta, choolu kuda daniki jealousy padutundi! 🧹",
    "Vadu antha pisinaraayadu, tea lo sugar badulu sweet matalu vestadu! ☕",
    "Atani love letter antha pazhadi, danlo inka fountain pen ink undi! ✍️",
    "Atani fridge antha khaali, danlo water jug matrame VIP laaga kurchundi! 🧊",
    "Ammayi antha fashionista, pajama vesukuni kuda ramp walk chestundi! 👗",
    "Pakkinti TV antha pazhadi, danlo Netflix badulu Doordarshan nadustundi! 📺",
    "Atani sense of humor antha waste, atanivi jokes meeda navvu '404 error' ani cheptadi! 😂",
    "Atani naukar antha badakamga untadu, tea cheyadaniki oka IPL season padutundi! ☕️",
    "Vadu antha smart, kani exam lo pen vadili calculator tecchadu! 🖌️",
    "Atani brain antha khaali, alochinche tappudu echo vastundi! 🧠",
    "Pakkinti kukka antha nammakamga untadi, chupinchadu! 🐶",
    "Atani face antha ajeeb, mirror kuda atanini chusi crack ayindi! 🪞",
    "Ammayi antha matladutundi, tan mundu FM radio kuda fail avtundi! 😜",
    "Atani dreams antha filmy, Hollywood ataniki script adugutundi! 🎬",
    "Atani charger antha waste, phone charge avvadaniki badulu discharge avtundi! 🔌",
    "Vadu antha challaga untadu, atanillu fridge avasaram ledu! ❄️",
    "Pakkinti naukar antha drama chestadu, Bollywood lo audition ivvochu! 🎭",
    "Atani phone screen antha pagilindi, dani meeda game kuda puzzle ga marindi! 📱",
    "Atani sense of humor antha dry, Sahara desert kuda siggu padutundi! 😅",
    "Vadu antha khadoos, atani moham meeda smile chudataniki Visa kavali! 😣",
    "Atani hairstyle antha pazhadi, 90s hero lu kuda atanini copy chestare! 💇",
    "Ammayi antha andam ga untadi, kani selfie filter lenidhe kaki kuda gurtinchadu! 😜",
    "Atani confidence antha, ataniki boss ki tea iste sare! 😎",
    "Pakkinti illu food antha waste, kukka kuda tinna taruvata parigettindi! 🍽️",
    "Atani vooru net antha slow, good morning inka vastundi! 📱",
    "Vadu antha badakamga untadu, ataniki kalalu kuda buffering lo untayi! 🤣",
    "Atani phone antha pazhadi, danlo Bluetooth badulu morse code nadustundi! 📡",
    "Atani bank balance antha low, UPI kuda ataniki sympathy chupistundi! 💳",
    "Vadu antha marichipoyetodu, tana girlfriend peru kuda Google chesukuntadu! 🤔",
    "Pakkinti cooler antha waste, galiki thodu ga chinta kuda vastundi! 🌬️",
    "Atani scooter antha khatara, road meeda vadili paripotundi! 🛵",
    "Ayana smartwatch vesukunadu, kani time chudataniki gadi adugutadu! ⌚",
    "Vadu antha marichipoyetodu, tana peru kuda Google chesukuntadu! 🤔",
    "Pakkinti AC antha waste, atanillu fan kuda pasina padutundi! 🌬️",
    "Atani pelli katha vachindi, kani ayana 'ippudu Tinder try cheyali' ani cheptadu! 😜",
    "Atani brain antha fast, kani ataniki life 2G speed meeda nadustundi! 📡",
    "Ammayi antha andam ga untadi, kani makeup lenidhe kaki kuda gurtinchadu! 💄",
    "Atani gym bag antha baruvu, kani danlo protein badulu samosa untadi! 🥟",
    "Vadu antha matladutadu, atan mundu radio kuda mounam ga untundi! 📻",
    "Atani kalalu antha peddavi, kani nidra chinna ga vastundi! 🌙",
    "Atani phone battery antha week, charger lenidhe jeevinchaledu! 😴",
    "Pakkinti juttu antha chetta, choolu kuda daniki jealousy padutundi! 😂",
    "Vadu antha pisinaraayadu, tea lo sugar badulu sweet matalu vestadu! 😜",
    "Atani love letter antha pazhadi, danlo inka fountain pen ink undi! 🤣",
    "Atani fridge antha khaali, danlo water jug matrame VIP laaga kurchundi! 😜",
    "Ammayi antha fashionista, pajama vesukuni kuda ramp walk chestundi! 😝",
    "Pakkinti TV antha pazhadi, danlo Netflix badulu Doordarshan nadustundi! 🤣",
    "Atani sense of humor antha waste, atanivi jokes meeda navvu '404 error' ani cheptadi! 😜",
    "Atani naukar antha badakamga untadu, tea cheyadaniki oka IPL season padutundi! 😂",
    "Vadu antha smart, kani exam lo pen vadili calculator tecchadu! 😜",
    "Atani brain antha khaali, alochinche tappudu echo vastundi! 🤣",
    "Pakkinti kukka antha nammakamga untadi, chupinchadu! 😝",
    "Atani face antha ajeeb, mirror kuda atanini chusi crack ayindi! 😜",
    "Ammayi antha matladutundi, tan mundu FM radio kuda fail avtundi! 😂",
    "Atani dreams antha filmy, Hollywood ataniki script adugutundi! 🤣",
    "Atani charger antha waste, phone charge avvadaniki badulu discharge avtundi! 😜",
    "Vadu antha challaga untadu, atanillu fridge avasaram ledu! 😂",
    "Pakkinti naukar antha drama chestadu, Bollywood lo audition ivvochu! 🤣",
    "Atani phone screen antha pagilindi, dani meeda game kuda puzzle ga marindi! 😜",
    "Atani sense of humor antha dry, Sahara desert kuda siggu padutundi! 😂",

    # Tamil Jokes - 100 (From your input)
    "Avan mobile antha cheap, call pannina shock adikkum! 😜",
    "Avan gym poran, ana nahi body paatha dumbbell kuda vekkapadum! 😂",
    "Pakkathu veedu Wi-Fi antha slow, kaaka signal pudikka mudiyala! 📖",
    "Avan antha, biryani la oru nahi elakkai pottu ooru muzhusa saapiduvaan! 🍛",
    "Avan bike horn antha loud, ooru naai ella moracha pannita! 📣",
    "Ponnu antha selfies, phone camera pochu nahi! 📸",
    "Avan plans antha perfect, execute pannurathu nahi time illa! 😅",
    "Avan phone antha old, WhatsApp typewriter maari odum! 📠",
    "Avan antha slow, avan kanavu nahi buffering la irukku! 😴",
    "Pakkathu amma antha pesura, ava vaai nahi FM radio! 🎙️",
    "Avan scooter antha khatara, road la vitutu nahi odipovaan! 🛵",
    "Avan smartwatch pottan, ana time paakka watch kekkuravan! ⌚️",
    "Avan antha forgetful, avan peru nahi Google pannuvaan! 🤔",
    "Pakkathu veedu AC antha waste, veetu fanu nahi verthu kettu! 🌈️",
    "Pellu kathai nahi, avan Tinder try pannuren nahi! 😜",
    "Avan mobile evlo sasta, call pannina shock adikkum da! 📱",
    "Avan gym poran nu solli, avan body ah paatha dumbbell kuda vekkapadum da! 🏋️",
    "Pakkathu veetu Wi-Fi evlo slow, kaaka signal pudikka mudiyama maadi mela ukkaranthu iruku da! 📶",
    "Avan evlo kanjoos, biryani la oru elakkai mattum potu ooru muzhusa saapiduvaan da! 🍲",
    "Avan bike horn evlo loud, ooru naai ella moracha pannitu irukku da! 📢",
    "Indha ponnu evlo selfies edukka, phone camera 'podhum da' nu sollum da! 📸",
    "Avan plans evlo perfect, aana execute panna time eh illa da! 📅",
    "Avan phone evlo pazhaya, WhatsApp athula typewriter maari odum da! 📠",
    "Avan evlo somberi, avan kanavugal kuda buffering la irukkum da! 😴",
    "Pakkathu amma evlo pesura, ava vaai oru FM radio pola 24 mani neram odum da! 🎙️",
    "Avan scooter evlo khatara, road la vitutu odipovaan da! 🛵",
    "Avan smartwatch pottan, aana time paakka watch ketkura da! ⌚",
    "Avan evlo marathi, avan peru kuda Google pannuvaan da! 🤔",
    "Pakkathu veetu AC evlo waste, avan veetla fan kuda verthu kottuthu da! 🌬️",
    "Avan kalyana katha pesunan, aana avan 'ippo Tinder try pannanum' nu sollura da! 😜",
    "Avan brain evlo fast, aana avan life 2G speed la odum da! 📡",
    "Indha ponnu evlo azhaga, aana makeup illama kaaka kuda athai therinjukadhu da! 💄",
    "Avan gym bag evlo kanama, aana athula protein illama samosa irukkum da! 🥟",
    "Avan kanavugal evlo periya, aana thoongurathu chinna thoonga da! 🌙",
    "Avan evlo dramebaaz, Bollywood avanukku role kudutha vekkapadum da! 🎬",
    "Avan car mileage evlo mosama, petrol pump la avanukku permanent address irukku da! ⛽",
    "Pakkathu veetu pullaiyungal evlo shaitan, shaitan kuda avangala paathu bayapadum da! 😈",
    "Avan hairstyle evlo ajeeb, chittu kuda athula koodu kattadhu da! 💇‍♂️",
    "Avan evlo lajalu, ponnu munadi 'Wi-Fi connect ayiduchu' nu sollura da! 😳",
    "Avan bank balance evlo low, ATM kuda avana paathu sirikkum da! 💸",
    "Avan nanbargal evlo mosam, WhatsApp group la kuda seen pannaranga da! 📱",
    "Indha ponnu evlo vegama, ava vaaila irunthu vaarthai vanthutta ooru muzhusa viral agidum da! 🔥",
    "Pakkathu veetu inverter evlo waste, current ponna athu kuda ninnu pogum da! 🔋",
    "Avan velai karan evlo somberi, tea podurathuku oru season agum da! ☕",
    "Avan confidence evlo high, interview la boss kittai salary kekkura da! 💼",
    "Avan evlo periya பொய்யன், avan solluratha Google kuda confuse agidum da! 🤥",
    "Avan fridge evlo khali, athula thanni bottle mattum VIP pola ukkandhu irukku da! 🧊",
    "Avan dress evlo tight, moochu vida zip thirakkanum da! 👕",
    "Indha ponnu evlo fashionista, saree katti kuda catwalk pannura da! 👗",
    "Pakkathu veetu TV evlo pazhaya, athula Netflix illama Doordarshan odum da! 📺",
    "Avan ooru net evlo slow, email anuppa pura anuppanum da! 🕊️",
    "Avan love letter evlo mokka, ponnu padichitu block pannita da! 💌",
    "Avan evlo unlucky, lottery jeyichathuku apuram ticket kaanama pochu da! 🎟️",
    "Avan veedu evlo chinna, AC potta ooru muzhusa kuliridum da! 🏠",
    "Avan evlo smart, aana exam la pen ah vitutu calculator eduthuttu vanthan da! 🖋️",
    "Avan brain evlo khali, yosikkum podhu echo ketkum da! 🧠",
    "Pakkathu veetu naai evlo setiaana, avan Wi-Fi password kuda sollathu da! 🐶",
    "Avan mugam evlo ajeeb, mirror kuda avana paathu odainju pochu da! 🪞",
    "Indha ponnu evlo pesura, ava munadi FM radio kuda fail agidum da! 🎤",
    "Avan kanavugal evlo filmy, Hollywood avan kittai script kekkum da! 🎥",
    "Avan charger evlo waste, phone charge agurathuku pathila discharge agidum da! 🔌",
    "Avan evlo kulir, avan veetla fridge thevai illai da! ❄️",
    "Pakkathu veetu velai karan evlo drama pannura, Bollywood la audition kudukalam da! 🎭",
    "Avan phone screen evlo udainju, athula game kuda puzzle ayiduchu da! 📱",
    "Avan sense of humor evlo dry, Sahara desert kuda vekkapadum da! 😅",
    "Avan evlo kadoos, avan vaaila siripu paakka Visa venum da! 😣",
    "Avan hairstyle evlo pazhaya, 90s hero kuda athai copy pannuranga da! 💇‍♂️",
    "Indha ponnu evlo azhaga, aana selfie filter illama kaaka kuda therinjukadhu da! 📸",
    "Avan confidence evlo, interview la boss kittai tea kekkura da! ☕",
    "Pakkathu veetu food evlo mosam, naai kuda saapitu odi pochu da! 🍽️",
    "Avan ooru net evlo slow, WhatsApp la good morning ippavum varuthu da! 📶",
    "Avan evlo somberi, avan kanavugal kuda buffering la irukkum da! 😴",
    "Avan phone evlo pazhaya, athula Bluetooth illama morse code odum da! 📡",
    "Avan bank balance evlo low, UPI kuda avanukku sympathy kaattum da! 💳",
    "Avan evlo marathi, avan girlfriend peru kuda Google pannuvaan da! 🤔",
    "Pakkathu veetu cooler evlo waste, kaatru kuda sariya varathu da! 🌬️",
    "Avan scooter evlo khatara, road la vitutu odipovaan da! 🛵",
    "Avan smartwatch pottan, aana time paakka watch ketkura da! ⌚",
    "Avan evlo marathi, avan peru kuda Google pannuvaan da! 🤔",
    "Pakkathu veetu AC evlo waste, avan veetla fan kuda verthu kottuthu da! 🌬️",
    "Avan kalyana katha pesunan, aana avan 'ippo Tinder try pannanum' nu sollura da! 😜",
    "Avan brain evlo fast, aana avan life 2G speed la odum da! 📡",
    "Indha ponnu evlo azhaga, aana makeup illama kaaka kuda athai therinjukadhu da! 💄",
    "Avan gym bag evlo kanama, aana athula protein illama samosa irukkum da! 🥟",
    "Avan evlo pesura, avan munadi radio kuda sumama irukkum da! 📻",
    "Avan kanavugal evlo periya, aana thoongurathu chinna thoonga da! 🌙",
    "Avan phone battery evlo weak, charger illama vaazha mudiyathu da! 🔋",
    "Pakkathu veetu mudi evlo jhadoo, jhadoo kuda athukku poramai padum da! 🧹",
    "Avan evlo kanjoos, tea la sakkarai illama sweetana vaarthai poduvan da! ☕",
    "Avan love letter evlo pazhaya, athula ippavum fountain pen ink irukku da! ✍️",
    "Avan fridge evlo khali, athula thanni jug mattum VIP pola ukkandhu irukku da! 🧊",
    "Indha ponnu evlo fashionista, pajama pottu kuda ramp walk pannura da! 👗",
    "Pakkathu veetu TV evlo pazhaya, athula Netflix illama Doordarshan odum da! 📺",
    "Avan sense of humor evlo mosam, avan jokes ku siripu '404 error' nu sollum da! 😂",
    "Avan velai karan evlo somberi, tea podurathuku oru IPL season agum da! ☕️",
    "Avan evlo smart, aana exam la pen ah vitutu calculator eduthuttu vanthan da! 🖌️",
    "Avan brain evlo khali, yosikkum podhu echo ketkum da! 🧠",
    "Pakkathu veetu naai evlo setiaana, kaatta mudiyathu da! 🐶",
    "Avan mugam evlo ajeeb, mirror kuda avana paathu udainju pochu da! 🪞",
    "Indha ponnu evlo pesura, ava munadi FM radio kuda fail agidum da! 😜",
    "Avan kanavugal evlo filmy, Hollywood avan kittai script kekkum da! 🎬",
    "Avan charger evlo waste, phone charge agurathuku pathila discharge agidum da! 🔌",
    "Avan evlo kulir, avan veetla fridge thevai illai da! ❄️",
    "Pakkathu veetu velai karan evlo drama pannura, Bollywood la audition kudukalam da! 🎭",
    "Avan phone screen evlo udainju, athula game kuda puzzle ayiduchu da! 📱",
    "Avan sense of humor evlo dry, Sahara desert kuda vekkapadum da! 😅",
    "Avan evlo kadoos, avan vaaila siripu paakka Visa venum da! 😣",
    "Avan hairstyle evlo pazhaya, 90s hero kuda athai copy pannuranga da! 💇",
    "Indha ponnu evlo azhaga, aana selfie filter illama kaakka kuda therinjukadhu da! 😜",
    "Avan confidence evlo, boss kittai tea kekkura da! 😎",
    "Pakkathu veetu food evlo mosam, naai kuda saapitu odi pochu da! 🍽️",
    "Avan ooru net evlo slow, good morning ippavum varuthu da! 📱",
    "Avan evlo somberi, avan kanavugal kuda buffering la irukkum da! 🤣",
    "Avan phone evlo pazhaya, athula Bluetooth illama morse code odum da! 📡",
    "Avan bank balance evlo low, UPI kuda avanukku sympathy kaattum da! 💳",
    "Avan evlo marathi, avan girlfriend peru kuda Google pannuvaan da! 🤔",
    "Pakkathu veetu cooler evlo waste, kaatru kuda sariya varathu da! 🌬️",
    "Avan scooter evlo khatara, road la vitutu odipovaan da! 🛵",
    "Avan smartwatch pottan, aana time paakka watch ketkura da! ⌚",
    "Avan evlo marathi, avan peru kuda Google pannuvaan da! 🤔",
    "Pakkathu veetu AC evlo waste, avan veetla fan kuda verthu kottuthu da! 🌬️",
    "Avan kalyana katha pesunan, aana avan 'ippo Tinder try pannanum' nu sollura da! 😜",
    "Avan brain evlo fast, aana avan life 2G speed la odum da! 📡",
    "Indha ponnu evlo azhaga, aana makeup illama kaaka kuda athai therinjukadhu da! 💄",
    "Avan gym bag evlo kanama, aana athula protein illama samosa irukkum da! 🥟",
    "Avan evlo pesura, avan munadi radio kuda sumama irukkum da! 📻",
    "Avan kanavugal evlo periya, aana thoongurathu chinna thoonga da! 🌙",
    "Avan phone battery evlo weak, charger illama vaazha mudiyathu da! 😴",
    "Pakkathu veetu mudi evlo jhadoo, jhadoo kuda athukku poramai padum da! 😂",
    "Avan evlo kanjoos, tea la sakkarai illama sweetana vaarthai poduvan da! 😜",
    "Avan love letter evlo pazhaya, athula ippavum fountain pen ink irukku da! 🤣",
    "Avan fridge evlo khali, athula thanni jug mattum VIP pola ukkandhu irukku da! 😜",
    "Indha ponnu evlo fashionista, pajama pottu kuda ramp walk pannura da! 😝",
    "Pakkathu veetu TV evlo pazhaya, athula Netflix illama Doordarshan odum da! 🤣",
    "Avan sense of humor evlo mosam, avan jokes ku siripu '404 error' nu sollum da! 😜",
    "Avan velai karan evlo somberi, tea podurathuku oru IPL season agum da! 😂",
    "Avan evlo smart, aana exam la pen ah vitutu calculator eduthuttu vanthan da! 😜",
    "Avan brain evlo khali, yosikkum podhu echo ketkum da! 🤣",
    "Pakkathu veetu naai evlo setiaana, kaatta mudiyathu da! 😝",
    "Avan mugam evlo ajeeb, mirror kuda avana paathu udainju pochu da! 😜",
    "Indha ponnu evlo pesura, ava munadi FM radio kuda fail agidum da! 😂",
    "Avan kanavugal evlo filmy, Hollywood avan kittai script kekkum da! 🤣",
    "Avan charger evlo waste, phone charge agurathuku pathila discharge agidum da! 😜",
    "Avan evlo kulir, avan veetla fridge thevai illai da! 😂",
    "Pakkathu veetu velai karan evlo drama pannura, Bollywood la audition kudukalam da! 🤣",
    "Avan phone screen evlo udainju, athula game kuda puzzle ayiduchu da! 😜",
    "Avan sense of humor evlo dry, Sahara desert kuda vekkapadum da! 😂",

    # Kannada Jokes - 100 (From your input)
    "Avana nahi mobile cheap, call bandre nahi shock hodedu! 😜",
    "Avanu nahi gym hoguttane, adhre nahi body nodi dumbbell kuda naachike! 😂",
    "Pakkada nahi Wi-Fi slow nahi, kaage signal nahi sigalla! 📖",
    "Avanu nahi, biryani nahi ondu nahi elakki haaki nahi ooru tinnutane! 🍛",
    "Avana nahi bike horn loud nahi, ooru nahi nayi gaLa morcha maadide! 📣",
    "Hudugi nahi selfies nahi, phone camera nahi sari illa! 📸",
    "Avana nahi plans perfect nahi, execute nahi time nahi illa! 😅",
    "Avana nahi phone old nahi, WhatsApp typewriter nahi hage nahi nadutte! 📠",
    "Avanu nahi slow nahi, avana nahi kanasugaLu nahi buffering nahi aagide! 😴",
    "Pakkada nahi amma nahi maathana nahi, FM radio nahi! 🎙️",
    "Avana nahi scooter khatara nahi road nahi bittu nahi odihogu! 🛵",
    "Avanu nahi smartwatch haakidane, aadre nahi time nodalu nahi watch keluttane! ⌚️",
    "Avanu nahi forgetful nahi, avana nahi hesaru nahi Google maaduttane! 🤔",
    "Pakkada nahi mane AC waste nahi, fanu nahi bisilu nahi bittide! 🌈️",
    "Avana nahi maduve nahi Tinder try nahi maaduttene nahi! 😜",
    "Avana mobile estu sasta, call bandre current shock hoditade! 📱",
    "Avanu gym ge hogtini antaan, aadre avana body nodi dumbbell kuda naachike padtade! 🏋️",
    "Pakka maneya Wi-Fi estu slow, kaage signal sigde terrace mele kootu bittide! 📶",
    "Avanu estu kanjoosu, biryani yalli ondu elakki haaki full oorige oota haaktane! 🍲",
    "Avana bike horn estu loud, oorina naayigalu morcha maadidavu! 📢",
    "Ee hudugi estu selfies tegittaale, phone camera 'saaku kanre' antaan! 📸",
    "Avana plans estu perfect, aadre execute maadakke time sigalla! 📅",
    "Avana phone estu haleyadu, WhatsApp adralli typewriter tarah nadeyutte! 📠",
    "Avanu estu sustu, avana kanasugalige kuda buffering aagutte! 😴",
    "Pakka maneya aunty estu maathanaaduvaLu, avara baayi FM radio haage 24 ghante nadeyutte! 🎙️",
    "Avana scooter estu khatara, raste mele bittu odihoguttane! 🛵",
    "Avanu smartwatch haakidane, aadre time nodalu ghadi keluttane! ⌚",
    "Avanu estu marivantha, avana hesaru kuda Google maaduttane! 🤔",
    "Pakka maneya AC estu waste, avana maneyalli fan kuda uriyuttade! 🌬️",
    "Avana maduve katha banditu, aadre avanu 'naanu ippaga Tinder try maaduttene' antaan! 😜",
    "Avana brain estu fast, aadre avana life 2G speed alli nadeyutte! 📡",
    "Ee hudugi estu sundara, aadre makeup illade kaage kuda avana gurtisalla! 💄",
    "Avana gym bag estu bhari, aadre adralli protein badalu samosa irutte! 🥟",
    "Avana kanasugalu estu dodda, aadre nidde chikkadagi barutte! 🌙",
    "Avanu estu dramebaaz, Bollywood avanige role kottare naachike paduttade! 🎬",
    "Avana car mileage estu kharab, petrol pump nalli avanige permanent address ide! ⛽",
    "Pakka maneya makkalu estu shaitani, shaitana kuda avarannu nodi bayapaduttane! 😈",
    "Avana hairstyle estu ajeeb, hakki kuda adralli goodu kattalla! 💇‍♂️",
    "Avanu estu sharmishta, hudugi munde 'Wi-Fi connect aagide' antaan! 😳",
    "Avana bank balance estu low, ATM kuda avanige naguttade! 💸",
    "Avana dostharu estu mosagalu, WhatsApp group nalli kuda seen maadalla! 📱",
    "Ee hudugi estu bega, avana baayinda maatu bandre oorige viral aagutte! 🔥",
    "Pakka maneya inverter estu waste, current hodaaga adu kuda off aagutte! 🔋",
    "Avana naukar estu sustu, chaha maadakke ondu season tegadkondu! ☕",
    "Avana confidence estu high, interview nalli boss hatra salary keluttane! 💼",
    "Avanu estu dodda sullugar, avana maathininda Google kuda confuse aagutte! 🤥",
    "Avana fridge estu khali, adralli neerina bottle mattra VIP tarah kootide! 🧊",
    "Avana clothes estu tight, usiru tegiyoke zip tegi beku! 👕",
    "Ee hudugi estu fashionista, saree hakidaga kuda catwalk maaduttaale! 👗",
    "Pakka maneya TV estu haleyadu, adralli Netflix badalu Doordarshan nadeyutte! 📺",
    "Avana oorina net estu slow, email kalisoke kabootar kalisbeku! 🕊️",
    "Avana love letter estu ghatiya, hudugi odi block maadidlu! 💌",
    "Avanu estu unlucky, lottery geleya mele ticket kalisihoyitu! 🎟️",
    "Avana mane estu chikka, AC haakidre full ooru tandage aagutte! 🏠",
    "Avanu estu smart, aadre exam nalli pen bittu calculator tegedkondu bandan! 🖋️",
    "Avana brain estu khali, yochisuvaga echo kelutte! 🧠",
    "Pakka maneya nayi estu wafadar, avana Wi-Fi password kuda helalla! 🐶",
    "Avana mukha estu ajeeb, kannadi kuda avanannu nodi odeduhoyitu! 🪞",
    "Ee hudugi estu maathanaaduvaLu, avala munde FM radio kuda fail aagutte! 🎤",
    "Avana kanasugalu estu filmy, Hollywood avanige script keluttade! 🎥",
    "Avana charger estu waste, phone charge aagovudu badalu discharge aagutte! 🔌",
    "Avanu estu tamma, avana maneyalli fridge avashyakate illa! ❄️",
    "Pakka maneya naukar estu drama maaduttane, Bollywood nalli audition kodabahudu! 🎭",
    "Avana phone screen estu hodedide, adralli game kuda puzzle aagide! 📱",
    "Avana sense of humor estu dry, Sahara desert kuda naachike paduttade! 😅",
    "Avanu estu khadoos, avana mukha mele smile nodalu Visa beku! 😣",
    "Avana hairstyle estu haleyadu, 90s hero galu kuda adannu copy maaduttare! 💇‍♂️",
    "Ee hudugi estu sundara, aadre selfie filter illade kaage kuda avana gurtisalla! 📸",
    "Avana confidence estu, interview nalli boss hatra coffee keluttane! ☕",
    "Pakka maneya oota estu kharab, nayi kuda tindu odihoyitu! 🍽️",
    "Avana oorina net estu slow, WhatsApp nalli good morning ippaga kuda barutte! 📶",
    "Avanu estu sustu, avana kanasugalige kuda buffering aagutte! 😴",
    "Avana phone estu haleyadu, adralli Bluetooth badalu morse code nadeyutte! 📡",
    "Avana bank balance estu low, UPI kuda avanige sympathy torisutte! 💳",
    "Avanu estu marivantha, avana girlfriend hesaru kuda Google maaduttane! 🤔",
    "Pakka maneya cooler estu waste, gali jote bhayavannu kuda tegibittu! 🌬️",
    "Avana scooter estu khatara, raste mele bittu odihoguttane! 🛵",
    "Avanu smartwatch haakidane, aadre time nodalu ghadi keluttane! ⌚",
    "Avanu estu marivantha, avana hesaru kuda Google maaduttane! 🤔",
    "Pakka maneya AC estu waste, avana maneyalli fan kuda uriyuttade! 🌬️",
    "Avana maduve katha banditu, aadre avanu 'naanu ippaga Tinder try maaduttene' antaan! 😜",
    "Avana brain estu fast, aadre avana life 2G speed alli nadeyutte! 📡",
    "Ee hudugi estu sundara, aadre makeup illade kaage kuda avana gurtisalla! 💄",
    "Avana gym bag estu bhari, aadre adralli protein badalu samosa irutte! 🥟",
    "Avanu estu maathanaaduvaLu, avana munde radio kuda nishabdavagutte! 📻",
    "Avana kanasugalu estu dodda, aadre nidde chikkadagi barutte! 🌙",
    "Avana phone battery estu weak, charger illade jeevisalu sadhya illa! 🔋",
    "Pakka maneya keshagaLu estu jhadu, jhadu kuda adakke poramai paduttade! 🧹",
    "Avanu estu kanjoosu, chaha nalli sakkare badalu sihi maathugalannu haakuttane! ☕",
    "Avana love letter estu haleyadu, adralli ippaga kuda fountain pen ink ide! ✍️",
    "Avana fridge estu khali, adralli neerina jug mattra VIP tarah kootide! 🧊",
    "Ee hudugi estu fashionista, pajama haaki kuda ramp walk maaduttaale! 👗",
    "Pakka maneya TV estu haleyadu, adralli Netflix badalu Doordarshan nadeyutte! 📺",
    "Avana sense of humor estu mosam, avana jokes ge naagu '404 error' antaan! 😂",
    "Avana naukar estu sustu, chaha maadakke ondu IPL season tegadkondu! ☕️",
    "Avanu estu smart, aadre exam nalli pen bittu calculator tegedkondu bandan! 🖌️",
    "Avana brain estu khali, yochisuvaga echo kelutte! 🧠",
    "Pakka maneya nayi estu wafadar, toosalla! 🐶",
    "Avana mukha estu ajeeb, kannadi kuda avanannu nodi odeduhoyitu! 🪞",
    "Ee hudugi estu maathanaaduvaLu, avala munde FM radio kuda fail aagutte! 😜",
    "Avana kanasugalu estu filmy, Hollywood avanige script keluttade! 🎬",
    "Avana charger estu waste, phone charge aagovudu badalu discharge aagutte! 🔌",
    "Avanu estu tamma, avana maneyalli fridge avashyakate illa! ❄️",
    "Pakka maneya naukar estu drama maaduttane, Bollywood nalli audition kodabahudu! 🎭",
    "Avana phone screen estu hodedide, adralli game kuda puzzle aagide! 📱",
    "Avana sense of humor estu dry, Sahara desert kuda naachike paduttade! 😅",
    "Avanu estu khadoos, avana mukha mele smile nodalu Visa beku! 😣",
    "Avana hairstyle estu haleyadu, 90s hero galu kuda adannu copy maaduttare! 💇",
    "Ee hudugi estu sundara, aadre selfie filter illade kaage kuda avana gurtisalla! 😜",
    "Avana confidence estu, boss hatra tea keluttane! 😎",
    "Pakka maneya oota estu kharab, nayi kuda tindu odihoyitu! 🍽️",
    "Avana oorina net estu slow, WhatsApp nalli good morning ippaga kuda barutte! 📱",
    "Avanu estu sustu, avana kanasugalige kuda buffering aagutte! 🤣",
    "Avana phone estu haleyadu, adralli Bluetooth badalu morse code nadeyutte! 📡",
    "Avana bank balance estu low, UPI kuda avanige sympathy torisutte! 💳",
    "Avanu estu marivantha, avana girlfriend hesaru kuda Google maaduttane! 🤔",
    "Pakka maneya cooler estu waste, gali jote bhayavannu kuda tegibittu! 🌬️",
    "Avana scooter estu khatara, raste mele bittu odihoguttane! 🛵",
    "Avanu smartwatch haakidane, aadre time nodalu ghadi keluttane! ⌚",
    "Avanu estu marivantha, avana hesaru kuda Google maaduttane! 🤔",
    "Pakka maneya AC estu waste, avana maneyalli fan kuda uriyuttade! 🌬️",
    "Avana maduve katha banditu, aadre avanu 'naanu ippaga Tinder try maaduttene' antaan! 😜",
    "Avana brain estu fast, aadre avana life 2G speed alli nadeyutte! 📡",
    "Ee hudugi estu sundara, aadre makeup illade kaage kuda avana gurtisalla! 💄",
    "Avana gym bag estu bhari, aadre adralli protein badalu samosa irutte! 🥟",
    "Avanu estu maathanaaduvaLu, avana munde radio kuda nishabdavagutte! 📻",
    "Avana kanasugalu estu dodda, aadre nidde chikkadagi barutte! 🌙",
    "Avana phone battery estu weak, charger illade jeevisalu sadhya illa! 😴",
    "Pakka maneya keshagaLu estu jhadu, jhadu kuda adakke poramai paduttade! 😂",
    "Avanu estu kanjoosu, chaha nalli sakkare badalu sihi maathugalannu haakuttane! 😜",
    "Avana love letter estu haleyadu, adralli ippaga kuda fountain pen ink ide! 🤣",
    "Avana fridge estu khali, adralli neerina jug mattra VIP tarah kootide! 😜",
    "Ee hudugi estu fashionista, pajama haaki kuda ramp walk maaduttaale! 😝",
    "Pakka maneya TV estu haleyadu, adralli Netflix badalu Doordarshan nadeyutte! 🤣",
    "Avana sense of humor estu mosam, avana jokes ge naagu '404 error' antaan! 😜",
    "Avana naukar estu sustu, chaha maadakke ondu IPL season tegadkondu! 😂",
    "Avanu estu smart, aadre exam nalli pen bittu calculator tegedkondu bandan! 😜",
    "Avana brain estu khali, yochisuvaga echo kelutte! 🤣",
    "Pakka maneya nayi estu wafadar, toosalla! 😝",
    "Avana mukha estu ajeeb, kannadi kuda avanannu nodi odeduhoyitu! 😜",
    "Ee hudugi estu maathanaaduvaLu, avala munde FM radio kuda fail aagutte! 😂",
    "Avana kanasugalu estu filmy, Hollywood avanige script keluttade! 🤣",
    "Avana charger estu waste, phone charge aagovudu badalu discharge aagutte! 😜",
    "Avanu estu tamma, avana maneyalli fridge avashyakate illa! 😂",
    "Pakka maneya naukar estu drama maaduttane, Bollywood nalli audition kodabahudu! 🤣",
    "Avana phone screen estu hodedide, adralli game kuda puzzle aagide! 😜",
    "Avana sense of humor estu dry, Sahara desert kuda naachike paduttade! 😂",

    # Punjabi Jokes - 100 (From your input)
    "Usda nahi mobile sasta nahi call band ta nahi jhatka lagda nahi! 😜",
    "Oh nahi gym janda nahi, par nahi body vekh ke nahi dumbbell nahi sharma jave nahi! 😂",
    "Padosi da nahi Wi-Fi slow nahi, kauwa nahi signal nahi fadne nahi chad ditta nahi! 📖",
    "Oh nahi kanjo nahi, biryani nahi bas nahi ek nahi elaichi nahi saara nahi kha lega nahi! 🍛",
    "Usdi nahi bike da horn nahi loud nahi, pind de nahi kutte nahi morcha kadh ditta nahi! 📣",
    "Kudi nahi selfies nahi leti nahi, phone da nahi camera nahi thak gya nahi! 😜",
    "Usde nahi plan perfect nahi, bas nahi execute nahi time nahi milda nahi! 😅",
    "Usda nahi phone purana nahi, WhatsApp nahi typewriter nahi warga nahi chalda nahi! 📠",
    "Oh nahi sust nahi, usde nahi sapne nahi buffering nahi ch aande nahi! 😴",
    "Padosi nahi aunty bol di nahi, muh nahi FM radio nahi chalda nahi! 🎙️",
    "Usda nahi scooter khatara nahi, sadak te nahi chhad ke nahi bhaj janda nahi! 🛵",
    "Oh nahi smartwatch paya nahi, par nahi time vekhan nu nahi ghadi mangda nahi! ⌚️",
    "Oh nahi bhulakkad nahi, apna nahi naam nahi Google karda nahi! 🤔",
    "Padosi da nahi AC kharab nahi, ghar ch nahi pankha nahi pasina nahi karda nahi! 🌈️",
    "Usdi nahi shaadi di nahi baat nahi, oh nahi Tinder try nahi karda nahi! 😜",
    "Usda mobile ena sasta, call vi lag kare ta jhatka lagda! 📱",
    "Oh gym janda kehnda, par ohdi body vekh ke dumbbell vi sharma jave! 🏋️",
    "Padosi da Wi-Fi ena slow, kauwe ne signal fadne layi chhat te behna chhad ditta! 📶",
    "Saala ena kanjoos, biryani ch ik elaichi paake poora pind kha juga! 🍲",
    "Ohdi bike da horn ena loud, pind de kuttaya ne morcha kadh ditta! 📢",
    "Oh kudi eniyan selfies lendi, phone da camera kehnda – bas kar de! 📸",
    "Bhai de plan ene pakke, bas execute karan da time kade na aave! 📅",
    "Ohda phone ena purana, WhatsApp ohde te typewriter wangu chalda! 📠",
    "Oh banda ena sust, ohde supne vi buffering ch aande ne! 😴",
    "Padosan eni bolchal, ohde muh da FM radio 24 ghante chalda! 🎙️",
    "Saale da scooter ena khatara, sadak te chhad ke bhaj janda! 🛵",
    "Bhai ne smartwatch payi, par time vekhan layi ghadi mangda! ⌚",
    "Oh banda ena bhulakkad, apna naam vi Google karda! 🤔",
    "Padosi da AC ena kharab, ohde ghar ch pankha vi pasina karda! 🌬️",
    "Ohdi shaadi di gal challi, par oh kehnda – hale ta Tinder try karna! 😜",
    "Bhai da dimag ena tez, par ohdi zindagi 2G speed te chaldi! 📡",
    "Oh kudi eni sohni, par makeup bina kauwa vi na pehchane! 💄",
    "Saale da gym bag ena bhaari, par ohde ch protein di jagah samosa niklda! 🥟",
    "Bhai de supne ene vadde, par neend choti jehi aundi! 🌙",
    "Oh banda ena dramebaaz, Bollywood ohnu role deke sharma jave! 🎬",
    "Ohdi car da mileage ena kharab, petrol pump te permanent address aa! ⛽",
    "Padosi de bache ene shaitan, shaitan vi ohna nu vekh ke darr jave! 😈",
    "Bhai da hairstyle ena ajeeb, chidiya vi ohde te ghonsla nahi banaundi! 💇‍♂️",
    "Oh banda ena sharma, kudi de saamne kehnda – Wi-Fi connect ho gya! 😳",
    "Saale da bank balance ena low, ATM vi ohde te hasda! 💸",
    "Bhai de dost ene bewafa, WhatsApp group ch vi seen nahi karde! 📱",
    "Oh kudi eni tez, ohde muh cho gal nikldi te pind tak viral ho jandi! 🔥",
    "Padosi da inverter ena kharab, bijli jandi aa te oh vi band ho janda! 🔋",
    "Ohda naukar ena sust, chah banan ch poora season nikal janda! ☕",
    "Bhai da confidence ena high, interview ch boss ton salary mangda! 💼",
    "Oh banda ena bada jhootha, ohdiyan galla te Google vi confuse ho jave! 🤥",
    "Saale da fridge ena khaali, ohde ch sirf paani di bottle VIP baithi aa! 🧊",
    "Bhai de kapde ene tight, saah len layi zip kholni paindi! 👕",
    "Oh kudi eni fashionista, saari paake vi catwalk kardi! 👗",
    "Padosi da TV ena purana, ohde te Netflix di jagah Doordarshan chalda! 📺",
    "Ohde pind da net ena slow, email bhejan layi kabootar bhejna painda! 🕊️",
    "Bhai da love letter ena ghatiya, kudi ne padh ke block kar ditta! 💌",
    "Oh banda ena unlucky, lottery jittan ton baad ticket kho gya! 🎟️",
    "Saale da ghar ena chota, AC laya ta poora mohalla thanda ho gya! 🏠",
    "Oh banda ena smart, par exam ch pen chhad ke calculator le aaya! 🖋️",
    "Bhai da dimag ena khaali, echo sunayi dindi jad sochda! 🧠",
    "Padosi da kutta ena wafadar, saale da Wi-Fi password vi nahi dasda! 🐶",
    "Ohdi shakal eni ajeeb, mirror vi ohnu vekh ke crack ho gya! 🪞",
    "Oh kudi eni boldi, ohde saamne FM radio vi fail ho jave! 🎤",
    "Bhai de supne ene filmy, Hollywood ohnu script mangda! 🎥",
    "Saale da charger ena kharab, phone charge hon di bajaye discharge ho janda! 🔌",
    "Oh banda ena thanda, ohde ghar ch fridge di lod nahi! ❄️",
    "Padosi da naukar ena drama karda, Bollywood ch audition de sakda! 🎭",
    "Ohda phone da screen ena tuteya, ohde te game vi puzzle ban jandi! 📱",
    "Bhai da sense of humor ena dry, Sahara desert vi sharma jave! 😅",
    "Oh banda ena khadoos, ohde muh te smile vekhan layi Visa lagda! 😣",
    "Saale da hairstyle ena purana, 90s de hero vi ohnu copy karde ne! 💇‍♂️",
    "Oh kudi eni sohni, par selfie filter bina kauwa vi na pehchane! 📸",
    "Bhai da confidence ena, interview ch boss ton chah mangda! ☕",
    "Padosi de ghar da khana ena kharab, kutta vi kha ke bhaj gya! 🍽️",
    "Ohde pind da net ena slow, WhatsApp te good morning hale tak aunda! 📶",
    "Oh banda ena sust, ohde supne vi buffering ch aande ne! 😴",
    "Bhai da phone ena purana, ohde ch Bluetooth di bajaye morse code chalda! 📡",
    "Saale da bank balance ena low, UPI vi ohnu sympathy dikhaundi! 💳",
    "Oh banda ena bhulakkad, apni girlfriend da naam vi Google karda! 🤔",
    "Padosi da cooler ena kharab, hawa de naal sathiya vi nikal aunda! 🌬️",
    "Saale da scooter ena khatara, sadak te chhad ke bhaj janda! 🛵",
    "Bhai ne smartwatch payi, par time vekhan layi ghadi mangda! ⌚",
    "Oh banda ena bhulakkad, apna naam vi Google karda! 🤔",
    "Padosi da AC ena kharab, ohde ghar ch pankha vi pasina karda! 🌬️",
    "Ohdi shaadi di gal challi, par oh kehnda – hale ta Tinder try karna! 😜",
    "Bhai da dimag ena tez, par ohdi zindagi 2G speed te chaldi! 📡",
    "Oh kudi eni sohni, par makeup bina kauwa vi na pehchane! 💄",
    "Saale da gym bag ena bhaari, par ohde ch protein di jagah samosa niklda! 🥟",
    "Oh banda ena bolda, ohde saamne radio vi chup ho jave! 📻",
    "Bhai de supne ene vadde, par neend choti jehi aundi! 🌙",
    "Ohda phone di battery eni weak, charger bina jee nahi sakda! 🔋",
    "Padosi de baal ene jhadoo, jhadu vi ohnu jealous aa! 🧹",
    "Oh banda ena kanjoos, chah ch shakkar di bajaye mitthiyan galla paunda! ☕",
    "Bhai da love letter ena purana, ohde ch hale vi fountain pen di ink aa! ✍️",
    "Saale da fridge ena khaali, ohde ch sirf paani da jug VIP baitha aa! 🧊",
    "Oh kudi eni fashionista, pajama paake vi ramp walk kardi! 👗",
    "Padosi da TV ena purana, ohde te Netflix di jagah Doordarshan chalda! 📺",
    "Bhai da sense of humor ena bekar, ohde jokes te hassi kehndi – 404 error! 😂",
    "Ohda naukar ena sust, chah banan ch poora IPL season nikal janda! ☕️",
    "Oh banda ena smart, par exam ch pen chhad ke calculator le aaya! 🖌️",
    "Bhai da dimag ena khaali, echo sunayi dindi jad sochda! 🧠",
    "Padosi da kutta ena wafadar, dikhan nahi dinda! 🐶",
    "Ohdi shakal eni ajeeb, mirror vi ohnu vekh ke crack ho gya! 🪞",
    "Oh kudi eni boldi, ohde ditta FM radio vi fail ho janda! 😜",
    "Bhai de supne ene filmy, Hollywood vi ohnu script mangda! 🎬",
    "Saale da charger ena kharab, phone charge hon di bajaye discharge ho janda! 🔌",
    "Oh banda ena thanda, ohde ghar ch fridge di lod nahi! ❄️",
    "Padosi da naukar ena drama karda, Bollywood ch audition de sakda! 🎭",
    "Ohda phone da screen ena tuteya, ohde te game vi puzzle ban jandi! 📱",
    "Bhai da sense of humor ena dry, Sahara desert vi sharma jave! 😅",
    "Oh banda ena khadoos, ohde muh te smile vekhan layi Visa lagda! 😣",
    "Saale da hairstyle ena purana, 90s de hero vi ohnu copy karde ne! 💇",
    "Oh kudi eni sohni, par selfie filter bina ditta kau! 😜",
    "Bhai da confidence ena, ditta boss nahi chah aa! 😎",
    "Padosi de ghar da khana ena kharab, kutta vi kha ke bhaj gya! 🍽️",
    "Ohde pind da net ena slow, good morning hale tak aunda! 📱",
    "Oh banda ena sust, ohde ditta supne da buffering! 🤣",
    "Bhai da phone ena purana, ohde ch Bluetooth di bajaye ditta morse code chalda! 📡",
    "Saale da bank balance ena low, UPI vi ohnu sympathy dikhaundi! 💳",
    "Oh banda ena bhulakkad, apni girlfriend da naam vi Google karda! 🤔",
    "Padosi da cooler ena kharab, hawa de naal sathiya vi nikal aunda! 🌬️",
    "Ohda scooter ena khatara, sadak te chhad ke bhaj janda! 🛵",
    "Bhai ne smartwatch payi, par time vekhan layi ghadi mangda! ⌚",
    "Oh banda ena bhulakkad, apna naam vi Google karda! 🤔",
    "Padosi da AC ena kharab, ohde ghar ch pankha vi pasina karda! 🌬️",
    "Ohdi shaadi di gal challi, par oh kehnda – hale ta Tinder try karna! 😜",
    "Bhai da dimag ena tez, par ohdi zindagi 2G speed te chaldi! 📡",
    "Oh kudi eni sohni, par makeup bina kauwa vi na pehchane! 💄",
    "Saale da gym bag ena bhaari, par ohde ch protein di bajaye samosa niklda! 🥟",
    "Oh banda ena bolda, ohde saamne radio vi chup ho jave! 📻",
    "Bhai de supne ene vadde, par neend choti jehi aundi! 🌙",
    "Oh bhais eni sust, hain na ghar ch jo vade de naal aundi! 😴",
    "Saara itta rauka chahida, ki vi syara? 😜",
    "Chhora de chhora ena aa, bolda ohde ditta! 😜",
    "Bhai da supna chota, ki vi us ditta! 😂",
    "Oh banda ena sust, ohde supne ch vi buffering kare! 😴",
    "Ohda naukar ena chalaak, chah banan ch poora T20 khel janda! ☕",
    "Saale da bank balance ena low, ATM ohnu loan offer karda! 💸",
    "Bhai da love letter ena bekar, kudi ne padh ke Wi-Fi band kar ditta! 📴",
    "Oh kudi eni selfies lendi, phone da front camera retire mangda! 📸",
    "Padosi de ghar da inverter ena bekar, bijli jandi aa te band ho janda! 🔋",
    "Ohde pind da net ena slow, WhatsApp te good night hale tak aunda! 🌙",
    "Bhai da confidence ena high, interview ch boss ton selfie mangda! 🤳",
    "Oh banda ena kanjoos, pizza de ik slice ch poora din nikal dinda! 🍕",
    "Saale da fridge ena khaali, ohde ch paani di bottle vi ikalli baithi aa! 🧊",
]


@app.on_message(filters.command("joke"))
async def joke(_, message: Message):
    A = await message.reply_text("Fetching a joke for you... 😂")
    
    joke_text = random.choice(JOKES)
    target_mention = "" 
    
    command_issuer_id = message.from_user.id 
    
    # 1. Check for direct mentions in the command text
    if message.entities:
        for entity in message.entities:
            if entity.type == MessageEntityType.MENTION:
                mentioned_username = message.text[entity.offset : entity.offset + entity.length].strip('@')
                try:
                    user_obj = await app.get_users(mentioned_username)
                    if user_obj.id != command_issuer_id: # Only tag if not the command issuer
                        target_mention = user_obj.mention
                        break 
                except Exception:
                    pass 
            elif entity.type == MessageEntityType.TEXT_MENTION:
                if entity.user:
                    if entity.user.id != command_issuer_id: # Only tag if not the command issuer
                        target_mention = entity.user.mention
                        break 
    
    # 2. If no direct mention found, check if it's a reply
    if not target_mention and message.reply_to_message:
        if message.reply_to_message.from_user:
            replied_user = message.reply_to_message.from_user
            if replied_user.id != command_issuer_id: # Only tag if not the command issuer
                target_mention = replied_user.mention

    # Construct the caption based on new formatting requirement:
    # 🤡 From (link): Joke Text @Mention (everything on one line)

    final_caption = f"🤡 **[Fʀᴏᴍ](https://t.me/FcKU4Baar)**: {joke_text}"
    
    # If a target mention exists, append it directly after the joke text with a space
    if target_mention:
        final_caption += f" {target_mention}" # Add a space before the mention

    await A.edit(final_caption, disable_web_page_preview=True)


__MODULE__ = "Jᴏᴋᴇ"
__HELP__ = """
/joke - Gᴇᴛ ᴀ ʀᴀɴᴅᴏᴍ ᴊᴏᴋᴇ.
/joke @username - Tᴀɢ ᴛʜᴇ ᴍᴇɴᴛɪᴏɴᴇᴅ ᴜsᴇʀ (ɪғ ɴᴏᴛ ᴄᴏᴍᴍᴀɴᴅ ɪssᴜᴇʀ) ᴡɪᴛʜ ᴀ ʀᴀɴᴅᴏᴍ ᴊᴏᴋᴇ.
/joke (reply to user) - Tᴀɢ ᴛʜᴇ ʀᴇᴘʟɪᴇᴅ ᴜsᴇʀ (ɪғ ɴᴏᴛ ᴄᴏᴍᴍᴀɴᴅ ɪssᴜᴇʀ) ᴡɪᴛʜ ᴀ ʀᴀɴᴅᴏᴍ ᴊᴏᴋᴇ."""
